### ISSUE TITLE
support html format settings

### ISSUE THREAD

**Issue by ctf0** [shufo/vscode-blade-formatter#1]
is that possible ? the format settings are under `HTML › Format`

**Comment by shufo** [comment]
@ctf0 
Currently supported only Indent Size setting via `Blade Formatter > Format > Indent Size`.
![image](https://user-images.githubusercontent.com/1641039/88352040-51886000-cd93-11ea-9add-2644a5e04927.png)

It is using js-beautify internally, so have plan to support js-beautify's html format options.

**Comment by ctf0** [comment]
oh ok, thanx for ur help.
