### ISSUE TITLE
php format

### ISSUE THREAD

**Issue by 1pix** [shufo/vscode-blade-formatter#11]
Hi there,

Would it be possible to format code between php directive (@php ... @endphp) with php formatter ?
sometimetimes usefull, exemple for a multi-array $template var in wordpress gutenberg block..
a bit hard to read when flated, as blade-formatter remove the "manual" indent/format on save.
```blade
{{--
  Title: Section featuredImg + 2cols
  Category: lalibellule
  Icon: admin-comments
  Keywords: section columns image
  Mode: preview
  SupportsMode: false
  SupportsMultiple: true
  SupportsInnerBlocks: true
--}}
@php
$template = [
[ 'core/columns', ['className' => 'l-SiteRow l-SiteRow--332'], [
['core/column', ['className' => 'l-SiteCol'], [
['cgb/block-fib']
]],
[ 'core/column', ['className' => 'l-SiteCol'],[
[ 'core/paragraph', [ 'placeholder' => 'Entrer du contenu...' ] ],
]],
[ 'core/column', ['className' => 'l-SiteCol'],[
[ 'core/paragraph', [ 'placeholder' => 'Entrer du contenu...' ] ],
]],
]]
];
@endphp

<section data-{{ $block['id'] }} class="l-SectionCols">
  <InnerBlocks template="<?= esc_attr( wp_json_encode($template)) ?>" />
</section>
```
Anyway, thank you for the best blade formatter out there  !
Best.

**Comment by AlexMorrisonDev716** [comment]
This is also my #1 feature request for this extension. Great work!!

**Comment by SpiZeak** [comment]
For me this is the only thing missing, really love this extension.
Thank you guys!!

**Comment by 1pix** [comment]
Hi there, I saw that php formatting option is in your todo list, great ! so not sure if this issue is still necessary, but give it an Up to stay informed ;) (Please close it if not needed). Again thank you so much to the team for the good work. Stay well.

**Comment by 1pix** [comment]
seems already done with #201 !

**Comment by 1pix** [comment]
seems already done in https://github.com/shufo/blade-formatter/pull/201#issue-563616138

**Comment by shufo** [comment]
Ah, I forgot to close the issue, thanks for reporting the issue @1pix !

Now you can format template like this.

```blade
@php
if ($user) {
$foo = ["aaa", "bbb", "ccc"];
foreach($users as $user){
  echo $user->id;
}
}
@endphp
```

to 

```blade
@php
if ($user) {
    $foo = ['aaa', 'bbb', 'ccc'];
    foreach ($users as $user) {
        echo $user->id;
    }
}
@endphp
```
