### ISSUE TITLE
Parse Error : syntax error, unexpected '{' on line 1 > 1 | <?php echo new Intl.NumberFormat('fr-FR', { style: 'currency', currency: 'EUR' }).format(payload.amount) ?> | ^

### ISSUE THREAD

**Issue by rtfulrich** [shufo/vscode-blade-formatter#149]
This is the code inside my blade file : @{{ new Intl.NumberFormat('fr-FR', { style: 'currency', currency: 'EUR' }).format(payload.amount) }}

It refuses to format the file as it consideres that the curly braces at the second parameter of Intl.NumberFormat is unexpected.

**Comment by shufo** [comment]
Expression in curly braces in blade considered as PHP expression so it must be valid as PHP code.
That's why raises 
```
Parse Error : syntax error, unexpected '{' on line 1 > 1 | <?php echo new Intl.NumberFormat('fr-FR', { style: 'currency', currency: 'EUR' }).format(payload.amount) ?> | ^
```

**Comment by shufo** [comment]
Sorry for the late reply. 
Thanks for reporting the issue @rtfulrich

This issue is fixed at https://github.com/shufo/vscode-blade-formatter/releases/tag/v0.10.1.
