### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by goncoolio** [shufo/vscode-blade-formatter#169]
- Issue Type: `Bug`
- Extension Name: `vscode-blade-formatter`
- Extension Version: `0.7.19`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.58.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by orangedigitalweb** [comment]
{{-- <p>
                        @php
                            $str = '';
                        @endphp
                        @foreach ($vkyc as $dd)
                            @php $str.=ucfirst($dd).', ';@endphp
                        @endforeach
                        {{ rtrim($str, ', ') }}
                    </p> --}}
