### ISSUE TITLE
UNRESPONSIVE extension host 

### ISSUE THREAD

**Issue by bailianhua** [shufo/vscode-blade-formatter#179]
## Template

Expansion hang trying to format the file

## Context (Environment)
My VS code build 
Version: 1.58.2 (system setup)
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:10:15.214Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.22000
## Description
When trying to format the blade file both by format function or format on save the extension just going into infinite loading. It seem update 1.58 break it. I try go back to 1.57 and it works for awhile then vscode do the automatic update and it broke again. 

But the second time rolling back to 1.57 didn't work anymore.

**Comment by inap-bannai** [comment]
+1
