### ISSUE TITLE
unacceptable formatting for php functions

### ISSUE THREAD

**Issue by Forsakenrox** [shufo/vscode-blade-formatter#199]
Before:
![image](https://user-images.githubusercontent.com/11795286/131359849-459e7649-fc79-47da-a944-94c9a70ec814.png)
After:
![image](https://user-images.githubusercontent.com/11795286/131359923-b4cfa6d9-61d3-42f5-96d6-0baceeb154c2.png)

This behavior is unacceptable, also this line stay untouched some updates before. I was try to install different outdated versions of extension, but has no result, Also - wrap line lenght set for 100000000 symbols.

**Comment by formikaio** [comment]
+1

**Comment by shufo** [comment]
Hi @Forsakenrox. 
Sorry for late reply and thanks for reporting the issue.
This issue is fixed at https://github.com/shufo/vscode-blade-formatter/releases/tag/v0.12.0
