### ISSUE TITLE
Replaces empty class attribute with some waired text

### ISSUE THREAD

**Issue by iyashpal** [shufo/vscode-blade-formatter#206]
## Template

**Please write your blade template that occurs issues.**

## Context (Environment)

Version: 1.60.0 (user setup)
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:41:52.311Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

## Description
Before formatting :

![blade-formatter-before](https://user-images.githubusercontent.com/19922707/132124148-0649e707-94e6-4dd8-b100-b776cfb9ee36.png)

After Formatting :

![blade-formatter-after](https://user-images.githubusercontent.com/19922707/132124161-e2f37f81-bddb-484f-b55c-8f96589b78ab.png)

**Comment by shufo** [comment]
Thanks @iyashpal 
Just released fix as https://github.com/shufo/vscode-blade-formatter/releases/tag/v0.7.28.

**Comment by iyashpal** [comment]
Thank you very much
