### ISSUE TITLE
Can not format blade: "Check if temp is too complicated or not"

### ISSUE THREAD

**Issue by mobayen** [shufo/vscode-blade-formatter#21]
## Template

```

@extends('layouts/app')

@section('content')
    @if ($x)
        asdasd
    @endif
@endsection

```

## Context (Environment)

Can't format blade: something goes wrong. Please check if template is too complicated or not. Or simplify template might solves issue.

- write your environment

try to format

**update1**: it happens when I set the "**bladeFormatter.format.wrapAttributes**" to "**force-expand-multiline**",

**update2**: after a file formatted once, all attempts to format throws this error! no matter what is the wrapAttribute value

**Comment by prodv** [comment]
Facing same issue.

"indent_size": 4,
"wrap_line_length": 120,
"wrap_attributes": "auto"

**Comment by prodv** [comment]
Only the creator can solve this issue.
