### ISSUE TITLE
please remove line wrap on @set directive

### ISSUE THREAD

**Issue by formikaio** [shufo/vscode-blade-formatter#213]
## Template

For this sample line: 

`@set $myVariableWithVeryVeryVeryVeryVeryLongName = ($myFirstCondition || $mySecondCondition) ? 'My text' : 'My alternative text'`

the formatter adds a line wrap (result is 2 lines):

```
@set $myVariableWithVeryVeryVeryVeryVeryLongName = ($myFirstCondition || $mySecondCondition) ? 'My text' : 'My
alternative text'
```

so the page breaks.

## Context (Environment)

Please remove line wrap while formatting the @set directive ... it breaks pages!

**Comment by formikaio** [comment]
+1

**Comment by formikaio** [comment]
+1

**Comment by formikaio** [comment]
Still not fixed, still an issue preventing us from using this cool extension

**Comment by shufo** [comment]
Fixed by https://github.com/shufo/blade-formatter/issues/542
