### ISSUE TITLE
Can not found blade format after updated 

### ISSUE THREAD

**Issue by trungbanh** [shufo/vscode-blade-formatter#260]
file *.blade.php 

After updated vscode can not found blade format any more 

Window 10 and 11 visua studio code lastest version 

it bottleneck in the formater search step

**Comment by GoodM4ven** [comment]
Closing requested. @shufo

**Comment by shufo** [comment]
Closed for organizing purpose https://github.com/shufo/vscode-blade-formatter/issues/372
