### ISSUE TITLE
Error in escaped JS with Array.prototype.map()

### ISSUE THREAD

**Issue by akinka** [shufo/vscode-blade-formatter#269]
## Template
```
<user-listing :data="{{ $data }}"
              :url="'{{ route('admin.users.index') }}'"
              v-cloak
              inline-template>
    ...
    <tr v-for="item in items"
            :key="item.id">
        ...
        <td>@{{ item . roles.map(role => role.name).join(', ') }}</td>
    </tr>
</user-listing>
```

## Context (Environment)
- Windows 10
- VS Code 1.63.0

## Description
Using Vue inside Blade.

Escaped JS code 
`@{{ item . roles.map(role => role.name).join(', ') }}`

Error: 
`Parse Error : syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')' on line 1 > 1 | <?php echo item . roles.map(role => role.name).join(', ') ?> | ^`

**Comment by shufo** [comment]
This behaviour is fixed at https://github.com/shufo/blade-formatter/releases/tag/v1.16.1.
Thanks @akinka for reporting the issue!
