### ISSUE TITLE
Case Label Format

### ISSUE THREAD

**Issue by drycrushader** [shufo/vscode-blade-formatter#274]
If I use `String` for case label. After I press `Shift` + `Alt` + `F`, a space added to case label.

## Expected
<pre>@foreach ($items as $item)
    @switch($item->status)
        @case("status")
            // Do something
        @break
    @endswitch
@endforeach</pre>

## Actual
<pre>@foreach ($items as $item)
    @switch($item->status)
        @case(" status")
            // Do something
        @break
    @endswitch
@endforeach</pre>

## Context (Environment)
- VSCode extension v0.8.4

**Comment by shufo** [comment]
@drycrushader 
Thanks for reporting the issue.
This behaviour is fixed at https://github.com/shufo/vscode-blade-formatter/releases/tag/v0.8.6
