### ISSUE TITLE
If Elseif Format

### ISSUE THREAD

**Issue by drycrushader** [shufo/vscode-blade-formatter#284]
If I use `@elseif` with `<` operator, after I press `Shift`+`Alt`+`F`, an abnormal format occurs.
If I use `>` operator, it goes well.

Only happened in `@elseif`, `@if` not affected.

## Expected
<pre>@if ($condition < 1)
    {{-- Do something --}}
@elseif ($condition < 2)
    {{-- Do something --}}
@elseif ($condition < 3)
    {{-- Do something --}}
@else
    {{-- Do something --}}
@endif
</pre>

## Actual
<pre>@if ($condition < 1)
    {{-- Do something --}}
@elseif ($condition < 2) {{-- Do something --}} @elseif ($condition < 3) {{-- Do something --}} @else {{-- Do something --}} @endif
</pre>

## Context (Environment)
- VSCode extension v0.8.6

**Comment by shufo** [comment]
@drycrushader 
Thanks for reporting the issue!
Fixed at https://github.com/shufo/vscode-blade-formatter/releases/tag/v0.9.2.
