### ISSUE TITLE
@slot without @endslot incorrect formatting

### ISSUE THREAD

**Issue by joe-mcpherson** [shufo/vscode-blade-formatter#304]
## Template

I have:
`    @component('components.article.intro')
        @slot('date', $article->formatDate)
        @slot('read_mins', $article->readTime)
        @if($author)
            @slot('authors', [
                ['link'=>$author_link,'name'=> $author]
            ])
        @endif
        @slot('intro_text'){!! $article->introduction !!}@endslot
    @endcomponent`

It formats to:
`            @component('components.article.intro')
                @slot('date', $article->formatDate)
                    @slot('read_mins', $article->readTime)
                        @if ($author)
                            @slot('authors', [['link' => $author_link, 'name' => $author]])
                            @endif
                            @slot('intro_text'){!! $article->introduction !!}@endslot
                            @endcomponent`

**Please write your blade template that occurs issues.**

## Context (Environment)

- write your environment

It should not indent if @endslot not provided

## Description

Any other informations

**Comment by shufo** [comment]
@joe-mcpherson 
Thanks for reporting the issue!
Just released https://github.com/shufo/vscode-blade-formatter/releases/tag/v0.10.2 with fixed this issue.

**Comment by joe-mcpherson** [comment]
Fantastic! Thank you :)
