### ISSUE TITLE
}}@endslot without space before @endslot breaks formating

### ISSUE THREAD

**Issue by joe-mcpherson** [shufo/vscode-blade-formatter#306]
## Template

If I have 
`@component('components.elements.button')
    @slot('href')/plant/details/{{ $plant->system_name }} @endslot
@endcomponent`

after  formatting it is:
`@component('components.elements.button')
    @slot('href')/plant/details/{{ $plant->system_name }}@endslot
    @endcomponent`

It should be: 
`@component('components.elements.button')
    @slot('href')/plant/details/{{ $plant->system_name }}@endslot
@endcomponent`

## Context (Environment)

- write your environment

## Description

If there is a space before @endslot then it works as expected

**Comment by shufo** [comment]
I think this behavior is fixed in the [latest version](https://github.com/shufo/vscode-blade-formatter/releases/tag/v0.13.0)

```blade
@component('components.elements.button') @slot('href')/plant/details/{{ $plant->system_name }} @endslot @endcomponent
```

will format into

```blade
@component('components.elements.button')
    @slot('href')
        /plant/details/{{ $plant->system_name }}
    @endslot
@endcomponent
```
