### ISSUE TITLE
Support for custom directives

### ISSUE THREAD

**Issue by sdon2** [shufo/vscode-blade-formatter#307]
## Support for custom directives

~~~
@permission('post.edit')
    <button class="btn btn-primary" onclick="editPost({{ $id }})">Edit Post</button>
@endpermission
~~~
## Description

It would be great if laravel blade formatter supports custom directives like the above one which will be available as part of Entrust library.

**Comment by shufo** [comment]
Finally, Custom Directive is supported at https://github.com/shufo/vscode-blade-formatter/releases/tag/v0.14.0!
Thank you for your patience.

**Comment by sdon2** [comment]
@shufo Thank you very much.
