### ISSUE TITLE
syntax error, unexpected ')' 

### ISSUE THREAD

**Issue by azhar007elhar** [shufo/vscode-blade-formatter#310]
## Template

**Please write your blade template that occurs issues.**
Parse Error : syntax error, unexpected ')' on line 3 1 | <?php 2 | $gras = "" ; > 3 | if(){ | ^ 4 | 5 | }else { 6 |

## Context (Environment)

- laravel blade 

## Description

Any other informations

**Comment by GoodM4ven** [comment]
Requesting closing for insufficient information. @shufo 

Also, please check this `github-actions` bot; I don't think it is closing these as it should...

**Comment by shufo** [comment]
Closed by https://github.com/shufo/vscode-blade-formatter/issues/372
