### ISSUE TITLE
[Bug] Keeps Adding extra Indendation on each Format

### ISSUE THREAD

**Issue by arun07as** [shufo/vscode-blade-formatter#357]
## Template
This is a highly simplified version of our code. Issue is reproducible on this code.
```blade
@section('content')
    @switch($setting->field_type)
        @case('texteditor')
            <textarea>
                {{ $setting->value }}
            </textarea>
        @break
    @endswitch
@endsection
```

## Context (Environment)

Each time the blade file is formatted, more intendation is added ( Please see attached gif )

## Description

In the gif, I am saving the file ( I have `"editor.formatOnSave": true` ). Each time I save, more indendation is added ( it never stops. It keeps adding more indendation each time I save ).
![blade-format](https://user-images.githubusercontent.com/17740186/154629366-59b8d6ee-4836-49c4-a453-ff957e4638fd.gif)
This only happens in very rare scenarios. The above code attached is one scenario in which I was able to reproduce the issue.

**Comment by shufo** [comment]
Hi @arun07as.
Thanks for reporting the issue and reproducing example.
I also able to reproduce this behaviour.

It seems this behaviour occurs on `textarea` only. Other tag like `div` or `p` don't reproduce this behaviour.

For workaround this, please keep blade brace in one line.

```blade
@section('content')
    @switch($setting->field_type)
        @case('texteditor')
            <textarea>{{ $setting->value }}</textarea>
        @break
    @endswitch
@endsection
```

It will results consistent result format.

I don't know why it reproduces only with `textarea`, but I'll look into it. Thanks!

**Comment by shufo** [comment]
I think I've figured out what's going on here. 
The `textarea` tag is interpreted as including spaces by browser, so js-beautify, which this extension depends on, is trying to keep spaces, resulting in unintended formatting.

So unless you want to include the prefix spaces in the textarea tag, you should use textarea tag without spaces like 

```blade
<textarea>{{ $setting->value }}</textarea>
````

Textarea with spaces like

```blade
                 {{ $setting->value }}
```

will results in below behaviour in browser.

![image](https://user-images.githubusercontent.com/1641039/154694866-87c6a462-2a12-4bd8-bb7a-53ae64956a81.png)

**Comment by shufo** [comment]
Fixed at https://github.com/shufo/vscode-blade-formatter/releases/tag/v0.13.6
