### ISSUE TITLE
:bell: Delete an issue with insufficient information

### ISSUE THREAD

**Issue by shufo** [shufo/vscode-blade-formatter#372]
## Description

There are a lot of issues with insufficient information, so I'll close them for the purpose of organization. 
If you need an issue in open status, please write detailed information.

**Comment by GoodM4ven** [comment]
I think a lot more issues need to be closed now...

**Comment by Ilyas294** [comment]
Parse Error : syntax error, unexpected '$item' (T_VARIABLE), expecting T_AS on line 1 > 1 | <?php foreach ($surah-> as $item) ?> | ^
