### ISSUE TITLE
crack code

### ISSUE THREAD

**Issue by sobu-1000** [shufo/vscode-blade-formatter#374]
!--begin::Form-- >

                                                <
                                                form method = "post"
                                                action = "{{ route('orders.update', Crypt::encrypt($data->id)) }}"
                                                accept - charset = "UTF-8"
                                                class = "kt-form"
                                                role = "form"
                                                enctype = "multipart/form-data"
                                                novalidate = "novalidate"
                                                id = "form_lead" >
                                                @method('PATCH') @csrf

                                                <
                                                div class = "kt-portlet__body" >
                                                <
                                                div class = "kt-form__section kt-form__section--first" >
                                                <
                                                div class = "row" >
                                                <
                                                div class = "form-group col-lg-8" >
                                                <
                                                table class = "table table-striped- table-bordered table-hover table-checkable"
                                                id = "kt_table_1" >
                                                <
                                                tr >
                                                <
                                                th > Name < /th> <
                                                td >
                                                <
                                                input type = "text"
                                                name = "name"
                                                class = "form-control"
                                                value = "{{ $data->name }}" / >
                                                <
                                                /td> <
                                                /tr>
                                                @php

**Comment by sourabh-1000** [comment]
same problem and one more problem ,that if i use this formatter then it convert @ into <blade> and output mashed code
