### ISSUE TITLE
<style></style> in blade

### ISSUE THREAD

**Issue by pkboom** [shufo/vscode-blade-formatter#385]
Hi, thanks for the package. I don't know if it's just me but when I use `style` in blade, the closing tag always adds one blank line before it.

## Template
```js
<style>
.some-background {
  background-color: red;
}
</style>
```

After formatting, it looks like this:

```js
<style>
.some-background {
  background-color: red;
}

</style>

```
## Context (Environment)
Version: 1.65.2
Plugin: 0.13.11
Laravel: 8.x
PHP: 8.x

**Comment by shufo** [comment]
@pkboom 
I think this is because js-beautify, which is used internally, inserts whitespace in the style tag as well when the end-with-newline option is enabled.
I think this is an unexpected behavior so I'll look into it. Thanks.

**Comment by shufo** [comment]
Fixed at https://github.com/shufo/vscode-blade-formatter/releases/tag/v0.14.6
