### ISSUE TITLE
Indent Type Support

### ISSUE THREAD

**Issue by HowdyMcGee** [shufo/vscode-blade-formatter#4]
Are there any plans to allow users to set indent size? Personally, I prefer tabs to spaces and the extension doesn't seem to inherit the file's preferred spacing method.

**Comment by shufo** [comment]
@HowdyMcGee 
You can set indent size from vscode options.

![image](https://user-images.githubusercontent.com/1641039/89367502-2814f000-d714-11ea-8623-9ed74f7b9120.png)

Tab support will introduce with next minor release or update.

You can also format blade files programatically by [blade-formatter](https://github.com/shufo/blade-formatter). It already supports tabs.
