### ISSUE TITLE
Space missing in ternaries

### ISSUE THREAD

**Issue by GoodM4ven** [shufo/vscode-blade-formatter#402]
## Problem

In Alpine.js directives, where a **javascript expression** is supposed to be provided, a ternary doesn't space correctly (after `?`):

```html
<div x-bind:class="imageLoaded ?'blur-none' : 'blur-3xl'">
    ...
</div>
```

![image](https://user-images.githubusercontent.com/81492351/164883214-31512b58-b01a-44bd-b1be-2e6e19cf189f.png)

## Expectation

A space is expected after `imageLoaded ?`, like so:

```html
<div x-bind:class="imageLoaded ? 'blur-none' : 'blur-3xl'">
    ...
</div>
```

## Extra Details

If I remember, the extension used to format it correctly in the past... But I'm not sure!

**Comment by shufo** [comment]
@GoodM4ven 
yes, It was formatted in past version but disabled in recent version cause some unexpected side effect happened.
I'll look into it.

**Comment by shufo** [comment]
Fixed at https://github.com/shufo/vscode-blade-formatter/releases/tag/v0.13.20
