### ISSUE TITLE
Wrong formatting of Inline JavaScript within blade directives => intentions will be lost

### ISSUE THREAD

**Issue by martin-braun** [shufo/vscode-blade-formatter#404]
## Template

```blade
<script>
    function test() {
        @if (Auth::check())
            if (window.test) {
            return;
            }
        @endif
    }
</script>
```

## Context (Environment)

- macOS 12.3.1 (21E258)

## Description

Formatting this template should cause the inline JS to format with proper intentions as well. `return;` should have a couple more spaces in front, so it's more to the right. So, the above should format to look like this: 

```blade
<script>
    function test() {
        @if (Auth::check())
            if (window.test) {
               return;
            }
        @endif
    }
</script>
```

But this won't happen. Here is a richer presentation of the problem:

<img width="546" alt="Screen Shot 2022-04-23 at 9 42 52 PM" src="https://user-images.githubusercontent.com/24259245/164944630-2947e75b-423b-4ed0-91f1-cc0f7e7791de.png">

See how all JS lines are on the same vertical plane level?

This happens when JS is inside of blade directives, in this case between `@if (Auth::check())` and `@endif`. As soon as I remove those lines, JS will be formatted correctly.

My current work-around is to put `{{-- blade-formatter-disable-next-line --}}` ahead of each directive in JS. Ugly, but better than keeping it this way. I hope this can be fixed, because this extension is the best choice for blade formatting so far.

**Comment by shufo** [comment]
Thanks @martin-braun for creating the issue.
I'll look into it.

**Comment by shufo** [comment]
Fixed at https://github.com/shufo/vscode-blade-formatter/releases/tag/v0.13.24

**Comment by martin-braun** [comment]
@shufo Thank you. I just updated, it works flawlessly, good work! Really appreciate it. :)
