### ISSUE TITLE
Nothing works (first time install, inside Blade files inside fresh Laravel project)

### ISSUE THREAD

**Issue by AgainPsychoX** [shufo/vscode-blade-formatter#407]
![image](https://user-images.githubusercontent.com/23557839/165736258-fbd78c2d-adc7-4fb1-9577-a92b270aa04c.png)

**Comment by GoodM4ven** [comment]
Try adding this to your JSON settings (without the comment and the dots):
```json
  ...
  // Blade
  "[blade]": {
    "editor.defaultFormatter": "shufo.vscode-blade-formatter"
  },
  ...
```

**Comment by GoodM4ven** [comment]
Also, what doesn't work exactly? I can see everything indented properly there!

**Comment by AgainPsychoX** [comment]
Sorry guys, it seems I am fucking stupid. I was wonder why the highlight isn't working after I installed the formatter, and it didn't work because the workspace I was in had no highlight extension enabled. After enabling those properly, everything works fine! Sorry for the issue.

**Comment by shufo** [comment]
@AgainPsychoX 
Never mind, thanks for creating the issue!

@GoodM4ven 
Thanks for the advice!
