### ISSUE TITLE
Filed to memory alocation

### ISSUE THREAD

**Issue by alwinfau** [shufo/vscode-blade-formatter#410]
## Template

**Please write your blade template that occurs issues.**

## Context (Environment)

- write your environment

## Description

Any other informations

**Comment by GoodM4ven** [comment]
面白くない

**Comment by GoodM4ven** [comment]
Closing requested.

**Comment by shufo** [comment]
Closed by https://github.com/shufo/vscode-blade-formatter/issues/372
