### ISSUE TITLE
HTML Attribute Sorting

### ISSUE THREAD

**Issue by GoodM4ven** [shufo/vscode-blade-formatter#413]
Greetings,

I'd assume that many people rely on this VSC [HTML Attributes Sorter](https://github.com/rbalet/vscode-attrs-sorter) extension to do just what it sounds like, but the repository is dead, and it has a lot of bugs with current Blade directives...

However, since our 先輩 has already considered Tailwind CSS class sorting, I thought he'd also consider HTML attribute sorting for this extension as well! 😉

What does *he* think? 🙂

**Comment by shufo** [comment]
Thanks @GoodM4ven for suggesting the feature.

It is may be out of the scope of this project, but I think it's fine to add HTML attribute sorting feature as an opt-in.
or if there is already an Extension that provides such functionality correctly for Blade, I think we should use that.

If there seems to be a problem with the existing Extensions, I'll try to add that feature.

**Comment by GoodM4ven** [comment]
Yep, I already tried all the available ones, I believe, and none would work properly with the current Blade directives and they're filled with bugs...

Please consider adding this feature, as it's a must with all wrapping styles where every attribute is NOT on its own line; when they're next to each other - having the advantage of compact code (more readable, in my opinion), things could get annoying without order.

**Comment by shufo** [comment]
@GoodM4ven 
Added Sort HTML Attributes option at https://github.com/shufo/vscode-blade-formatter/releases/tag/v0.17.0
https://github.com/shufo/vscode-blade-formatter#extension-settings

I've included some standard HTML Attribute sorting methods as a trial implementation. 

Custom order will be included in the upcoming release.

**Comment by GoodM4ven** [comment]
Congrats, man, this is HUGE!
I'll make sure to give feedback if things start to get weird! 😗
