### ISSUE TITLE
Formatter shows issue and not wirks if file includes  {!! $any !!} 

### ISSUE THREAD

**Issue by HeribertoGer** [shufo/vscode-blade-formatter#416]
## Syntax error

**Parse Error : syntax error, unexpected '!', expecting ';' on line 1 > 1 | <?php echo !! $any!! ?> | ^**

## VS code laravel \ file.blade.php

formatther fails if include response html using {!! $res !!}

**Comment by shufo** [comment]
@HeribertoGer 
Can you post entire template? thanks.

**Comment by GoodM4ven** [comment]
Closing requested.

**Comment by shufo** [comment]
Closed by https://github.com/shufo/vscode-blade-formatter/issues/372
