### ISSUE TITLE
I cant use this formatter

### ISSUE THREAD

**Issue by Kigamekun** [shufo/vscode-blade-formatter#419]
I cant use my vscode blade formatter in my vscode

**Comment by GoodM4ven** [comment]
- Make sure you're open file has `.blade.php` extension
- Ensure that `Laravel Blade formatter` by `Shuhei` is installed within the environment, by this VSC command:
  `>Extensions: Show Enabled Extensions`
- Make sure that your `>Preferences: Open Settings (JSON)` has the following settings (inside the main object):
```jsonc
   ...
   // Blade
  "[blade]": {
    "editor.defaultFormatter": "shufo.vscode-blade-formatter",
    "editor.tabSize": 4, // To override YOUR default tabSize
  },
  ...
```
