### ISSUE TITLE
Issue formatting script tags with tabs

### ISSUE THREAD

**Issue by giovdi** [shufo/vscode-blade-formatter#422]
## Template

Here's the code that doesn't format correctly

```
@section('content')
	<div class="container">
		<div class="row justify-content-center">
			<div class="col">
				<div class="btn-group float-end" role="group" aria-label="Basic example">
					<button type="button" onclick="addCol()" class="btn btn-sm btn-primary"><i class="fas fa-plus"></i> Add
						column</button>
				</div>
				<div class="row budget-lanes">
				</div>
			</div>
		</div>
	</div>
@endsection

<script>
 function addCol() {
  $.post('budget.ajaxColumn', {
   '_token': '{{ csrf_token() }}'
  }, function(data) {
   $('.budget-lanes').append('test');
  }).fail(function(jqXHR, textStatus) {
   alert('An error occurred. Please try again.')
  })
 }
</script>
```

## Context (Environment)

Plugin version: 0.14.1

Settings:
```
    "bladeFormatter.format.useTabs": true,
    "bladeFormatter.format.indentSize": 1,
```

Environment:
```
VSC Version: 1.67.1 (user setup)
Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d
Date: 2022-05-06T12:37:03.389Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19043
```

## Description

Indentation into `<script></script>` tags are by spaces instead of tabs.

**Comment by giovdi** [comment]
Well, yes if I set `"bladeFormatter.format.useTabs": true` 😁
It works like a charm in the `@section` part, but not in the script one

**Comment by Scemist** [comment]
Many updates, but it still not solved! 😢

**Comment by GoodM4ven** [comment]
> Many updates, but it still not solved! cry

Dude, that's not how open-source works!

First of all, the author doesn't profit off of this extension, so they're not compelled to do anything beyond what they feel like doing and what their time allows them to.

Second of all, there's literally no standard out there, as far as I'm concerned, for an indentation of `1`.

And most importantly, you're free to contribute with a PR if you're in that desperate need for it.

**Comment by shufo** [comment]
Thanks for patience. 

Fixed at https://github.com/shufo/vscode-blade-formatter/releases/tag/v0.17.0

**Comment by shufo** [comment]
Thanks for describing OSS ecosystem. @GoodM4ven 

It's my side project so I haven't receive any profit from it. So issues will prioritized by how its urgency. 
In PHP world there is popular PSR-2 coding standard and this convention recommends space indentation. So I prioritized other issues.

If something goes wrong, feel free to create PR!
