### ISSUE TITLE
Issues when formatting custom directives when using tabs

### ISSUE THREAD

**Issue by AlexeiCrr** [shufo/vscode-blade-formatter#424]
Given, this block of code

```
<div>
	<div>
		<div @class([
		    'some class',
		    'some other class',
		    'another class',
		])></div>
	</div>
</div>
```

When I try to format it using tabs, the formatter inserts spaces combined with tabs below the custom directive.

<img width="342" alt="image" src="https://user-images.githubusercontent.com/27196163/168888684-bc75a62d-0463-461b-ad39-9ad5625ccf91.png">

Ideally, I would see tabs only. 

my setup : 

```
{
	"indentSize": 1,
	"wrapAttributes": "force-expand-multiline",
	"wrapLineLength": 100,
	"endWithNewLine": false,
	"useTabs": true
}
```

**Comment by shufo** [comment]
Hi @AlexeiCrr 
Thanks for reporting the issue.
Currently Tab spacing is unstable, so as a workaround, I'd recommend setting useTabs to false and using space instead.

**Comment by GoodM4ven** [comment]
A #422 duplicate.

**Comment by shufo** [comment]
Fixed at https://github.com/shufo/vscode-blade-formatter/releases/tag/v0.17.0
