### ISSUE TITLE
Adding Comma after Laravel Syntax in Blade Causes Error

### ISSUE THREAD

**Issue by HannesEURESA** [shufo/vscode-blade-formatter#429]
Issue with Formatting the Code within a blade with Laravel Syntax. The problem is at the moment, that if threre is Laravel Syntax between divs, that after formatting the blade the extensions put automatically a comma at the end. This comma within a blade causes Errors so i have to disable the extension. Is there a way to decline putting a comma at the end? In Prettier i already put the trailing comma from Es5 to none. But still the comma appears after formatting.

Example:

@disabled(!auth()->user()->ownsTest($variable))if ($this->$variable) ... @else ... @endif 

after Formatting it looks like this:

@disabled(
!auth()
->user()
->ownsTest($variable),
)@if ($this->variable) ... @else ... @endif 

The comma after ownsTest is causing errors

**Comment by shufo** [comment]
Fixed at https://github.com/shufo/vscode-blade-formatter/releases/tag/v0.14.4
