### ISSUE TITLE
Parse Error : syntax error, unexpected ':', expecting ')' on line 1 > 1 | <?php echo func(max-width:768px) ?> | ^

### ISSUE THREAD

**Issue by tys-rahul** [shufo/vscode-blade-formatter#430]
## Template

**Please write your blade template that occurs issues.**

## Context (Environment)

- write your environment

## Description

Any other informations

**Comment by cgslivre** [comment]
In my case:

Parse Error : syntax error, unexpected ':', expecting ')' on line 1 > 1 | <?php echo func(max-width: 992px) ?> | ^

@section('css')
    <style>
        .card-body+.card-body {
            margin-top: 20px !important;
            padding-top: 20px !important;
            border-top: 1px solid #e3ebf6;
        }

        @media(max-width: 992px) {
            .remove-border-end-on-mobile {
                border-right: 0 none !important;
            }

            .remove-border-end-on-mobile .card-body {
                border-bottom: 1px solid #e3ebf6;
                padding-bottom: 20px !important;
            }
        }

    </style>
@endsection

**Comment by shufo** [comment]
Thanks @tys-rahul and @cgslivre for example code 
Fixed at https://github.com/shufo/vscode-blade-formatter/releases/tag/v0.14.5
