### ISSUE TITLE
Textarea formatting issue

### ISSUE THREAD

**Issue by MBM1607** [shufo/vscode-blade-formatter#432]
# Problem

textarea tag gets wrapped incorrectly.

## Environment
**vscode - 1.67.2**
**vscode-blade-formatter - 0.14.3**

OS: Pop!_OS 22.04 LTS x86_64 

## Settings

```json
"bladeFormatter.format.sortTailwindcssClasses": true,
"bladeFormatter.format.wrapLineLength": 100,
"bladeFormatter.format.wrapAttributes": "force-expand-multiline",
"bladeFormatter.format.indentSize": 2
```

## Attached
![image](https://user-images.githubusercontent.com/47133639/171424725-f743a49f-454d-4d75-a002-4e4cd987a057.png)

**Comment by shufo** [comment]
Thanks @MBM1607 
It's similar to https://github.com/shufo/vscode-blade-formatter/issues/414

**Comment by shufo** [comment]
Fixed at https://github.com/shufo/vscode-blade-formatter/releases/tag/v0.14.6

**Comment by MBM1607** [comment]
I finally got around to check this and its working like a charm now. Thank you so much @shufo .
