### ISSUE TITLE
Formatting issue for script tag

### ISSUE THREAD

**Issue by MBM1607** [shufo/vscode-blade-formatter#440]
# Problem

script tag attributes are un-indented when wrapped to multi-lines.

## Environment
**vscode - 1.67.2**
**vscode-blade-formatter - 0.14.6**

OS: Pop!_OS 22.04 LTS x86_64 

## Settings

```json
"bladeFormatter.format.sortTailwindcssClasses": true,
"bladeFormatter.format.wrapLineLength": 100,
"bladeFormatter.format.wrapAttributes": "force-expand-multiline",
"bladeFormatter.format.indentSize": 2
```

## Attached
![Screenshot from 2022-06-09 14-49-34](https://user-images.githubusercontent.com/47133639/173015041-bc2b2e22-45cc-4a99-9fe9-2634bc7eda64.png)

**Comment by MBM1607** [comment]
Here is how it should be, for reference
![Screenshot from 2022-06-09 14-49-43](https://user-images.githubusercontent.com/47133639/173015458-72f2e655-5017-45d6-835b-01b197887b83.png)

**Comment by shufo** [comment]
https://github.com/shufo/blade-formatter/pull/639 will be include next release.
please wait a little.

**Comment by MBM1607** [comment]
Thanks @shufo , keep up the good work.

**Comment by shufo** [comment]
Fixed at https://github.com/shufo/vscode-blade-formatter/releases/tag/v0.15.3
