### ISSUE TITLE
Formatter throws "syntax error, unexpected" about Popper/Tippy JS

### ISSUE THREAD

**Issue by Andre-ADPC** [shufo/vscode-blade-formatter#443]
## Template
I am using `laravel-popper` from [andcarpi](https://github.com/andcarpi/laravel-popper) and testing `laravel-blade-lottie` from [pys1992](https://github.com/pys1992/laravel-blade-lottie).

Here is a snippet of the very basic `home.blade.php` in question:
```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {{-- Other metas, favicons, links in head --}}

    <title>ADPC Home Test</title>
</head>
<body>
    <h1 class="font-headline font-bold text-adpc-black-base text-xl pt-10 pl-10">A Weird Home Page</h1>
       <div id="animContainer1" class="flex flex-col content-center items-center mt-5 mb-5 w-74 h-74">
          <div id="animContainer2" class="fixed bottom-5 left-5 content-center items-center mt-5 mb-5 w-44 h-46">
              <div class="w-44 h-44 z-20 object-scale-down bg-gray-300">
              <h2 class="text-center font-bold text-adpc-black-base"><span @popper(This works.)>Loading a GIF</span></h2>
              <img src="{{ asset('/storage/images/cod-laravel-logo.gif') }}" alt="GIF File" title="Laravel Logo">
          </div>
      </div>

    <div id="animContainer3" class="fixed bottom-5 right-5 content-center items-center mt-5 mb-0 w-44 h-46">
        <div class="w-44 h-46 z20 bg-blue-300">
            <h2 class="text-center font-bold text-adpc-black-base"><span @popper(This works too.)>Loading a Lottie</
             span></h2>
            <div class="w-44 h-44 content-center items-center lottie" 
              data-animation-path="\storage\lottiefiles\hello-lottie.json" data-anim-loop="true" data-name="lottie"></div>
          </div>
    </div>
   @include('popper::assets')
</body>
{{-- Prefetch and preload to be applied in due course --}}
<script src="https://cdnjs.com/libraries/lottie-web" type="image/svg+xml"></script>
</html>
```

## Context (Environment)
This is a Laravel 9.1 test app done on localhost, using Laravel's web-server.
### composer.json
The rest of composer.json is stock-standard. Only require + require-dev info might be relevant, I think.
```
"require": {
    "php": "^8.0.2",
    "andcarpi/laravel-popper": "^0.9.4",
    "guzzlehttp/guzzle": "^7.2",
    "laravel/framework": "^9.11",
    "laravel/sanctum": "^2.14.1",
    "laravel/tinker": "^2.7",
    "pys/laravel-blade-lottie": "^1.1"
},
"require-dev": {
    "fakerphp/faker": "^1.9.1",
    "laravel/sail": "^1.0.1",
    "mockery/mockery": "^1.4.4",
    "nunomaduro/collision": "^6.1",
    "phpunit/phpunit": "^9.5.10",
    "spatie/laravel-ignition": "^1.0"
},
```

### package.json
The head of package.json is also stock-standard.
```
"devDependencies": {
    "@tailwindcss/custom-forms": "^0.2.1",
    "@tailwindcss/forms": "^0.5.2",
    "axios": "^0.25",
    "laravel-mix": "^6.0.6",
    "laravel-mix-tailwind": "^0.1.2",
    "lodash": "^4.17.19",
    "postcss": "^8.1.14",
    "tailwindcss": "^3.1.2"
},
"dependencies": {
    "@popperjs/core": "^2.11.5",
    "tw-elements": "^1.0.0-alpha12"
}
```

## Description

If I use a Popper facade inside any HTML element in my blade files, the formatter produces the error given below.
If I remove the Popper facade, the error does not occur.
It seems the Formatter is interpreting the Popper directive as the wrong blade syntax, complaining about the `is` in the Popper directive itself.

### Error:
```
Parse Error : syntax error, unexpected 'is' (T_STRING), expecting ')' on line 1
> 1 | <?php echo func(This is a Popper Tooltip!) ?>
    |                     ^
```
The blade renders without issues in Firefox Dev, Chrome and Edge browsers.
However, it is becoming a hassle to close the Blade Formatter pop-up errors in VS Code every time `file-save` is applied.

The Pys package is giving me a bit of a headache on my system due to a CORS issue we are trying to resolve, but it is assumed that it does not play any role in the relationship between VS Code IDE and Blade Formatter.

Reference screen-shot
![Chrome-2022-06-13_18-22-03](https://user-images.githubusercontent.com/86864273/173376317-afe91d6d-1c40-4c81-8178-8c0c61dd3c78.png)

### If anything else is needed to assist you @shufo , let me know and I'll pass it through.
Thanks for all your work and effort with this cool VSC extension!

**Comment by shufo** [comment]
Thanks @Andre-ADPC for detailed information.
I'll look into it.

**Comment by shufo** [comment]
Fixed at https://github.com/shufo/vscode-blade-formatter/releases/tag/v0.15.2

**Comment by Andre-ADPC** [comment]
Thank you.
