### ISSUE TITLE
Script tag identing with space when tab is setted

### ISSUE THREAD

**Issue by Scemist** [shufo/vscode-blade-formatter#473]
## Context (Environment)

I have a simple .blade.php file that works fine with the extension.

The config is set to use tabs instead spaces, and the size is 1.

My `settings.json`

```json
"blade.format.enable": true,
"bladeFormatter.format.indentSize": 1,
"bladeFormatter.format.useTabs": true,
"bladeFormatter.format.wrapAttributes": "preserve",
"bladeFormatter.format.wrapLineLength": 1500,
```

My Blade Formatter version in VSCode is `v0.15.2`

## Description

Although the html and blade code works file, **the JavaScript inside <script> tag is idented with spaces, but respecting the identSize as 1**.

If I open the same code in a simple html file, the JavaScript ident occurs normally with tabs.

> What I hope is that the JavaScript ident uses tab too. Is a issue or I'm missing something?

```blade
<body>
	<div>
		<h1>Hello</h1>
	</div>

	<script>
	 const paradas = JSON.parse('{!! json_encode($viagem, JSON_UNESCAPED_UNICODE) !!}')

	 const mapa = new Mapa([
	  Object.values(paradas)[0].coordenadas.lat,
	  Object.values(paradas)[0].coordenadas.lng
	 ], [
	  Object.values(paradas).pop().coordenadas.lat,
	  Object.values(paradas).pop().coordenadas.lng
	 ])

	 mapa.showPositions(paradas)
	 mapa.showBreakpointOnClick()

	 const viagem = new Viagem(paradas)
	</script>
</body>
```

**Comment by shufo** [comment]
Might be related to #424

**Comment by GoodM4ven** [comment]
A #422 duplicate.
