### ISSUE TITLE
Taking way too long to format / won't format.

### ISSUE THREAD

**Issue by Jamiul-Bari** [shufo/vscode-blade-formatter#474]
## Template

**Please write your blade template that occurs issues.**
This is actually a smaller version of my blade file. 

```
<div>
<table>
<tr>
@if ($potRR == true)
                                <td wire:key='{{ $this->getRandomStr() }}'>
                                    -
                                </td>
                            @else
                                @if ($tasks->isNotEmpty())
                                @foreach ($tasks->where('id', '=', 1) as $task)
                                <p>dd</p>
                                @endforeach
                                @else
                                    <td wire:key='{{ $this->getRandomStr() }}'
                                        wire:click='openAssignTaskModal({{ $pot->id }})'>
                                        -
                                    </td>
                                @endif
                            @endif
</tr>
</table>
</div>
```

## Context (Environment)
The code won't format. And will show processing animation on top. It will also hang the version control tab.

Environment: macOS Monterey,  VS Code Version: 1.68.1, Plugin version: 0.15.2

## Description

I don't know why for some reason it just takes forever to format. I have checked the syntax. If my syntax is wrong, it always shows an error at the bottom. But this won't show any error either. The moving blue animation never stops and also the version control shows a clock icon. Then I have to quit VS Code and run it again. Please try to format it. You may get the same issue.

However, I remove `->where('id', '=', 1)` from `$tasks` it works! So, after removing that part the following code works

```
<div>
<table>
<tr>

@if ($potRR == true)
                                <td wire:key='{{ $this->getRandomStr() }}'>
                                    -
                                </td>
                            @else
                                @if ($tasks->isNotEmpty())
                                @foreach ($tasks as $task)
                                <p>dd</p>
                                @endforeach
                                @else
                                    <td wire:key='{{ $this->getRandomStr() }}'
                                        wire:click='openAssignTaskModal({{ $pot->id }})'>
                                        -
                                    </td>
                                @endif
                            @endif
</tr>
</table>
</div>
```

**Comment by shufo** [comment]
Thanks @Jamiul-Bari 
I'll look into it.

**Comment by Jamiul-Bari** [comment]
Updated the extension, but it still doesn't work? Does it work on your machine? Is there any caching issue here?

**Comment by Jamiul-Bari** [comment]
Okay. No problem. Take your time.

**Comment by shufo** [comment]
Fixed at https://github.com/shufo/vscode-blade-formatter/releases/tag/v0.15.3
