### ISSUE TITLE
Trailling Comma causes Errors

### ISSUE THREAD

**Issue by HannesEURESA** [shufo/vscode-blade-formatter#491]
Issue with Formatting the Code within a blade with Laravel Syntax. The problem is at the moment, that if threre is Laravel Syntax between divs, that after formatting the blade the extensions put automatically a comma at the end. This comma within a blade causes Errors so i have to disable the extension. Is there a way to decline putting a comma at the end? In Prettier i already put the trailing comma from Es5 to none. But still the comma appears after formatting.

Example:

span class="@if(count(auth()->user()->currentXY->shopsXY()) > 1) ml-24 @else ml-16 @endif">Test</span

after Formatting it looks like this:

span class="@if (count(
	  auth()->user()->currentXY->shopsXY(),
	 ) > 1) ml-24 @else ml-16 @endif">Test</span

The comma after shopsXY is causing errors. Why do the Formatter puts there a Comma? In Global config File threre was declined that no comma is set. Trailling Comma is set to None

**Comment by shufo** [comment]
Thanks @HannesEURESA 

I've seen this before. It's unexpected behavior when nested condition exists.

I'll look into it.

For workaround, un-inline condition.

```php
// controller
return view('viewname', ['shops' => auth()->user()>currentXY->shopsXY()]);
```

```blade
{{-- blade --}}
@if (count($shops) > 1) ml-24 @else ml-16 @endif
```

**Comment by shufo** [comment]
Fixed at https://github.com/shufo/vscode-blade-formatter/releases/tag/v0.16.3

**Comment by HannesEURESA** [comment]
Thanks :) 
but now after this fix, a new Error arrived, because the formatting part is now this structure:

@foreach (auth()->user()->currentxy->shops() as $shop) -> original line: code works
after formatting:
@foreach (auth()->user()->currentTeam->seasonTicketShops() 
as $shop)

the as $shop is pushing to the next line and this causes again an Error
