### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by jagdishprasad123** [shufo/vscode-blade-formatter#492]
- Issue Type: `Bug`
- Extension Name: `vscode-blade-formatter`
- Extension Version: `0.16.1`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.68.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by GoodM4ven** [comment]
Requesting to close this issue. 0 information given. @shufo

**Comment by shufo** [comment]
Closed by #372
