### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by PabloVegaAU** [shufo/vscode-blade-formatter#497]
- Issue Type: `Bug`
- Extension Name: `vscode-blade-formatter`
- Extension Version: `0.16.2`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.69.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

![image](https://user-images.githubusercontent.com/51180071/178645958-88e8e718-9ff1-459b-adb6-fc99b404e1ed.png)

**Comment by GoodM4ven** [comment]
Requesting to close this one. No relative information has been provided. @shufo

**Comment by shufo** [comment]
Closed by #372
