### ISSUE TITLE
Unexpected breaks 

### ISSUE THREAD

**Issue by HannesEURESA** [shufo/vscode-blade-formatter#501]
After fix to 0.16.3, a new Error arrived, because the formatting part is now this structure:

@foreach (auth()->user()->currentxy->shops() as $shop) -> original line: code works
after formatting:
@foreach (auth()->user()->currentxy->shops()
as $shop)

the as $shop is pushing to the next line and this causes again an Error

**Comment by shufo** [comment]
This fix will included in next release

**Comment by shufo** [comment]
Fixed at https://github.com/shufo/vscode-blade-formatter/releases/tag/v0.16.4
