### ISSUE TITLE
Spaces within arrows after Formatting

### ISSUE THREAD

**Issue by HannesEURESA** [shufo/vscode-blade-formatter#506]
After Formatting there are spaces within the Arrow:
the original code must be:
a class=“group ...” :active=“request()->routeIs(‘route’)“>

After Formatting there are spaces within the arrows:

a class=“group ...” :active=“request() - > routeIs(‘route’)“>

this causes Error States

**Comment by shufo** [comment]
It seems that the attribute prefixed with a colon is recognized as the attribute that should be formatted as JS. blade-formatter currently recognizes colon-prefixed attributes as JS expressions.

Normally PHP expressions does not make sense with colon prexied attributes in blade, so did you use a special use for them?

Can you paste the original code according to the issue template? Thanks.

**Comment by HannesEURESA** [comment]
```
@if ((!isset($teams) && count($team_requests) == 0) || (count($userteams) == 0 && count($team_requests) == 0))
					<a class="group hover:bg-vt-cyan col-span-10 transform overflow-hidden rounded-lg bg-white p-4 shadow-xl transition-all duration-300 ease-in-out hover:-translate-y-1 hover:opacity-70 sm:col-span-5 md:col-span-4 lg:col-span-3 2xl:col-span-2"
								style="min-height: 19rem;" href="#" :active="request()->routeIs('teams.members')">
						<div>
							<div class="mt-4 flex items-center justify-center group-hover:opacity-90">
								<img src="{{ asset('images/add_user_rafiki.svg') }}" alt="Verein verwalten" width="150">
							</div>
							<div class="text-center">
								<span class="text-vt-green text-center text-xl font-bold uppercase group-hover:text-white">3) (D)einem Verein zuordnen</span>
							</div>
							<p class="my-2 text-sm group-hover:text-white">Erst wenn du mindestens einem Verein zugeordnet bist, kannst du Vereinsticket richtig nutzen.</p>
						</div>
					</a>
				@endif
```

**Comment by shufo** [comment]
It looks a normal A tag, so I think you can't use php expressions in `:active`, are you using some 3rd party package for this?

```html
<a class="group hover:bg-vt-cyan col-span-10 transform overflow-hidden rounded-lg bg-white p-4 shadow-xl transition-all duration-300 ease-in-out hover:-translate-y-1 hover:opacity-70 sm:col-span-5 md:col-span-4 lg:col-span-3 2xl:col-span-2"
								style="min-height: 19rem;" href="#" :active="request()->routeIs('teams.members')">
						.... 
					</a>
```

If this tag is a blade component, then it's the correct syntax.

**Comment by HannesEURESA** [comment]
It´s a Component which controlls the class, whether a class is active or not. It set´s the class to active when the Route is true, then the class within the a tag changes.

**Comment by shufo** [comment]
If it is like form of `x-foo` described in [Laravel doc](https://laravel.com/docs/9.x/blade#manually-registering-package-components), then the php expression in the attribute will be correctly formatted.

Can you post the version of Laravel and definition of component?

**Comment by HannesEURESA** [comment]
`@props(['active'])

@php
    $classes = ($active ?? false)
            ? 'items-center text-lg bg-gray-100 text-vt-green focus:outline-none focus:border-white transition duration-150 ease-in-out box py-2'
            : 'items-center text-lg font-medium text-white focus:outline-none focus:text-gray-1000 transition duration-150 ease-in-out hover:text-vt-green hover:bg-gray-100';
@endphp

<a {{ $attributes->merge(['class' => $classes]) }}>
    {{ $slot }}
</a>

class SideBarNavLink extends Component
{
    /**
     * Ist die Route vom Nutzer ausgewählt
     *
     * @var bool
     */
    public $active;

    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct($active = false)
    {
        $this->active = $active;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|string
     */
    public function render()
    {
        return view('components.sidebar-nav-link', ['active' => $this->active]);
    }
}
`
