### ISSUE TITLE
Is a new attribute wrapping strategy possible or recommended?

### ISSUE THREAD

**Issue by Random72IsTaken** [shufo/vscode-blade-formatter#509]
Greetings to the maker of the best extension ever! 😁

I was recently switching between 2 wrapping strategies:

### (1) `force-aligned`

```html
<!-- Fonts -->
<link rel="preconnect"
      href="https://fonts.googleapis.com">
<link rel="preconnect"
      href="https://fonts.gstatic.com"
      crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Noto+Naskh+Arabic:wght@400;500;600;700&display=swap"
      rel="prefetch">
```

### (2) `force-expand-multiline`

```html
<!-- Fonts -->
<link
    rel="preconnect"
    href="https://fonts.googleapis.com"
>
<link
    rel="preconnect"
    href="https://fonts.gstatic.com"
    crossorigin
>
<link
    href="https://fonts.googleapis.com/css2?family=Noto+Naskh+Arabic:wght@400;500;600;700&display=swap"
    rel="prefetch"
>
```

## Observations

The **advantage** of strategy 1 is utilizing the first line along the tag for the first attribute, like `<link rel="preconnect"`, and then aligning other attributes exactly underneath it. And this will also save a lot of lines on the long run, and make the page shorter. The **disadvantage**, however, is not knowing clearly where the element ended because the ending `>` is on the last line and next to the last attribute!

The advantage of strategy 2 is exactly fixing the disadvantage of strategy 1; that ending is concise and clear on its own line. -Which helps in case you've got content in `<div>` elements, and where it's very clear where the element has started and where it has ended... On the other hand, imagine if it's just a small `<meta>` element with only 2 attributes inside! This (2) strategy will make it a 4 line element for no actual reason! And the pages will be very, very long, in my opinion!

## Suggestion

So... What I'm dreaming of here is a new mixed strategy, where it's capitalizing on both advantages in one:

```html
@props([
    'title' => null,
    'dir' => 'ltr',
    'fontClass' => '',
])

<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}"
      dir="{{ $dir }}"
>

<head>
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1"
    >
    <!-- CSRF Token -->
    <meta name="csrf-token"
          content="{{ csrf_token() }}"
    >
    @stack('meta')

    <!-- Favicon -->
    <link rel="shortcut icon"
          href="{{ asset('favicon.ico') }}"
    >

    <!-- Title -->
    @if ($title)
        <title>{{ $title . ' - ' . config('app.name') }}</title>
    @else
        <title>{{ config('app.name') }}</title>
    @endif

    <!-- Fonts -->
    <link rel="preconnect"
          href="https://fonts.googleapis.com"
    >
    <link rel="preconnect"
          href="https://fonts.gstatic.com"
          crossorigin
    >
    <link href="https://fonts.googleapis.com/css2?family=Noto+Naskh+Arabic:wght@400;500;600;700&display=swap"
          rel="prefetch"
    >
    @stack('fonts')

    <!-- Styles -->
    @livewireStyles
    @stack('styles')

    <!-- Head Scripts -->
    @stack('headScripts')
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>

<body class="{{ $fontClass }} antialiased">
    @goodLoader

    {{ $slot }}

    <!-- Body Scripts -->
    @livewireScripts
    @stack('bodyScripts')
</body>

</html>
```

Is it possible to implement this with *ease*? 😃

Moreover, do you think this is even worth it? What do you think would be wrong about it? Advantages, disadvantages? Or do you think we should be used to a specific famous standard so we can read more code from others? What are your thoughts?! lol

**Comment by shufo** [comment]
Thanks for the suggestion! @GoodM4ven 
I think adding more wrapping strategy is not a bad idea because there is no standard practice for wrapping html attributes. e.g. [google style guide](https://google.github.io/styleguide/htmlcssguide.html#HTML_Line-Wrapping) says line wrapping is optional.

It's not so difficult to implement that behaviour.

> What do you think would be wrong about it? Advantages, disadvantages?

I think the disadvantage of having more options is that there will be potential bugs and it will be harder for the team to agree on which strategy to choose. That's why I described this extension as just "opinionated formatter".
On the other hand, the advantages is more options we will have.

Overall, I would say it is worth implementing although it requires careful test.

**Comment by delta1186** [comment]
I think this would be a great opportunity to possibly implement the prettier `bracketSameLine` option.  This would allow you to just leave the `wrapAttributes` equal to auto.  Then if the `wrapLineLength` value is hit you would get something like this.

```html
<button @click.stop="sidebarOpen = true"
      class="border-r border-gray-200 px-4 text-gray-500 focus:bg-gray-100 focus:text-gray-600 focus:outline-none md:hidden"
      aria-label="Open Navigation"
>
      <x-icon-o-menu class="h-6 w-6" />
  </button>
```

**Comment by Henriquex25** [comment]
> Acho que essa seria uma ótima oportunidade para possivelmente implementar a `bracketSameLine`opção mais bonita. Isso permitiria que você apenas deixasse o `wrapAttributes`igual para auto. Então, se o `wrapLineLength`valor for atingido, você obterá algo assim.
> 
> ```
> <button @click.stop="sidebarOpen = true"
>       class="border-r border-gray-200 px-4 text-gray-500 focus:bg-gray-100 focus:text-gray-600 focus:outline-none md:hidden"
>       aria-label="Open Navigation"
> >
>       <x-icon-o-menu class="h-6 w-6" />
> </button>
> ```

good idea !

I'm looking forward to it!

**Comment by delta1186** [comment]
Was this auto closed or really not planned? Just curious.

**Comment by shufo** [comment]
@delta1186 
Uh sorry, it was Auto closed.

**Comment by delta1186** [comment]
Auto closed again?
