### ISSUE TITLE
Laravel blade file php block indent issue 

### ISSUE THREAD

**Issue by furiousjayed** [shufo/vscode-blade-formatter#524]
![code](https://user-images.githubusercontent.com/45084793/183791396-0ffd053f-af51-4f57-b4d9-6446bf792f7c.png)

**Comment by GoodM4ven** [comment]
I think what he's expecting is:
```html
@php
    $method = strtoupper($method);
@endphp

**Comment by shufo** [comment]
Fixed at https://github.com/shufo/vscode-blade-formatter/releases/tag/v0.19.1
