### ISSUE TITLE
ok

### ISSUE THREAD

**Issue by ochiroo8409** [shufo/vscode-blade-formatter#527]
## Template

**Please write your blade template that occurs issues.**

## Context (Environment)

- write your environment

## Description

Any other informations

**Comment by GoodM4ven** [comment]
@shufo Can you ban this guy or something? He keeps posting empty issues and those who watch the project would get notified for nothing! 😡

**Comment by shufo** [comment]
Maybe we should add github action that automatically close empty issues :sweat_smile:

**Comment by shufo** [comment]
Closed by #372
