### ISSUE TITLE
Formatter Not working for approx 1000 lines of code

### ISSUE THREAD

**Issue by Shubham044** [shufo/vscode-blade-formatter#531]
## Template

**Please write your blade template that occurs issues.**

@extends('layouts.master')
@section('content')
    <link rel="stylesheet" href="{{ asset('plugins/datatables-bs4/css/dataTables.bootstrap4.css') }}">
    <link rel="stylesheet" href="{{ asset('plugins/select2/css/select2.min.css') }}">
    
    <div class="row page-titles">

        <div class="col-md-3 align-self-center">
            <select name="hotelname" id="hotelname" class="form-control " data-placeholder="{{ __('Select HOtel') }}"
                data-dropdown-css-class="select2-primary">
                <option selected disabled>{{ __('Select Hotel') }}</option>
                @foreach ($hotels as $hotel)
                    <option value="{{ $hotel->id }}">{{ $hotel->hotelname }}</option>
                @endforeach
            </select>
        </div>
        <div class="col-md-3 align-self-center">
            <select name="food_category" id="food_category" class="form-control " data-placeholder="{{ __('Select Category') }}"
                data-dropdown-css-class="select2-primary">
                <option selected disabled>{{ __('Select Category') }}</option>
            </select>
        </div>

        <div class="col-md-2 align-self-center hide" id="restaurant_dropdown">
            <select name="dropdown_restaurant" id="dropdown_restaurant" class="form-control "
                data-placeholder="{{ __('Select Category') }}" data-dropdown-css-class="select2-primary">
                <option selected disabled>{{ __('Select Restaurant') }}</option>
            </select>
        </div>

        <div class="col-md-3 align-self-center">
            <select name="dropdown_extras" id="dropdown_extras" class="form-control "
                data-placeholder="{{ __('Select Menu') }}" data-dropdown-css-class="select2-primary">
                <option selected disabled>{{ __('Select Menu') }}</option>
            </select>
        </div>

        {{-- <div class="col-md-4 align-self-center text-right">
            <div class="d-flex justify-content-end align-items-center">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ url('admin/') }}">{{ __('backend.home') }}</a></li>
                    <li class="breadcrumb-item active">{{ __('Hotel Food Menus') }}</li>
                </ol>

                
            </div>
        </div> --}}
    </div>
    
    
    <div class="content user_page">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-primary card-outline">
                    <div class="card-body">

                        {{-- <-   ------------------------------------------------------------------ Breakfast Form section -----------------------------------------------------------   -> --}}

                        <form method="POST" id="breakfast-form" class="col-md-12" role="form"
                            enctype="multipart/form-data">
                            <input type="hidden" class="form_hotel_id" name="form_hotel_id">
                            <input type="hidden" class="menu_id" name="menu_id">
                            @csrf

                            <div class="row my-1 rounded pt-4 mb-2" style="background-color:#f5f5f5">
                                <div class="col-md-12 ml-5 row align-items-center">
                                    <div class="form-group col-md-12 align-items-center">
                                        <label class="control-label" for="chefRecommends">{{ __("You May Also Like It ") }}* </label>
                                        <span onclick="showHide()">
                                            <i class="fa fa-solid fa-angle-up upArrow ml-2" style="cursor: pointer; color:rgb(199, 41, 96); font-size: 22px;"></i>
                                            <i class="fa fa-solid fa-angle-down downArrow hide ml-2" style="cursor: pointer; color:rgb(199, 41, 96); font-size: 22px;"></i>
                                         </span>
                                    </div>
                                </div>
                                <div class="groupHideShow">
                                <div class="col-md-12 ml-5" id="breakfastYouMayLikeIt">

                                </div>
                                <div class="col-md-12 ml-5 my-3 row">
                                    <a onclick="add_lunch_chef_recommends()" class="btn btn-primary btn-xs" style="color:white;"><i
                                            class="fa fa-plus"></i> Add more * </a>
                                </div>

                            </div>

                            </div>
                            

                            <div id="config_breakfast_form_add" class="mb-2">
                                {{-- <div class="row my-1 pt-4 mb-2">
                                    <div class="col-md-12 ml-5 row">
                                        <div class="form-group col-md-12">
                                            <label class="control-label"
                                                for="extra">{{ __("Define Extra's ") }}*</label>
                                        </div>
                                    </div>

                                    <div class="col-md-12 ml-5" id="config_breakfast_define_extra">
                                        <div class="row col-md-12">
                                            <div class="col-md-3">
                                                <select name="category" id="category" class="form-control "
                                                    data-placeholder="{{ __('Select Category') }}"
                                                    data-dropdown-css-class="select2-primary">
                                                    <option selected disabled>{{ __('Select Category') }}</option>

                                                </select>
                                            </div>
                                            <div class="col-md-3">
                                                <div class="col-md-12 mb-6">
                                                    <div class="form-group extraLabels">
                                                        <div class="input-group">
                                                            <input type="text" name="config_bf_label"
                                                                id="config_bf_label" class="form-control" value=""
                                                                placeholder="{{ __('Label') }}" autocomplete="off"
                                                                data-parsley-required="true" />
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-3">
                                                <div class="col-md-12 mb-6">
                                                    <div class="form-group extraprice">
                                                        <div class="input-group">
                                                            <input type="text" name="config_bf_price"
                                                                id="config_bf_price" class="form-control" value=""
                                                                placeholder="{{ __('Price') }}" autocomplete="off"
                                                                data-parsley-required="true" />
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                </div> --}}
                            </div>

                            {{-- <div class="w-100 mx-auto save_btn">
                                <button type="submit" class="btn btn-info " id="lunch_dinner_save"><span
                                        class="spinner-grow spinner-grow-sm formloader" style="display: none;"
                                        role="status" aria-hidden="true"></span> {{ __('backend.Save') }}</button>
                                <a href="{{ url('admin/hotels') }}" class="btn btn-default back"><span
                                        class="spinner-grow spinner-grow-sm formloader" style="display: none;"
                                        role="status" aria-hidden="true"></span> {{ __('backend.Back') }}</a>
                            </div> --}}
                        </form>

                        {{-- <-   ------------------------------------------------------------ Lunch & Dinner Form section ------------------------------------------------------------   -> --}}

                        <form method="POST" id="lunch-form" class="col-md-12 hide" role="form"
                            enctype="multipart/form-data">
                            <input type="hidden" class="form_hotel_id" name="form_hotel_id">
                            <input type="hidden" class="lunch_list_id" name="lunch_list_id">
                            <input type="hidden" class="menu_id" name="menu_id">

                            @csrf
 
                            <div class="row my-1 rounded pt-4 mb-2" style="background-color:#f5f5f5">
                                <div class="col-md-12 ml-5 row align-items-center">
                                    <div class="form-group col-md-12 align-items-center">
                                        <label class="control-label" for="chefRecommends">{{ __("Chef Recommend's ") }}* </label>
                                        <span onclick="showHide()">
                                            <i class="fa fa-solid fa-angle-up upArrow ml-2" style="cursor: pointer; color:rgb(199, 41, 96); font-size: 22px;"></i>
                                            <i class="fa fa-solid fa-angle-down downArrow hide ml-2" style="cursor: pointer; color:rgb(199, 41, 96); font-size: 22px;"></i>
                                         </span>
                                    </div>
                                </div>
                            <div class="groupHideShow">
                                <div class="col-md-12 ml-5" id="chef-recommends">
                                    
                                </div>
                                <div class="col-md-12 ml-5 my-3 row">
                                    <a onclick="add_lunch_chef_recommends()" class="btn btn-primary btn-xs" style="color:white;"><i
                                            class="fa fa-plus"></i> Add more Chef Recommends</a>
                                </div>

                            </div>

                            </div>

                            <div id="config_lunch_form_add" class="mb-2">

                            </div>

                            <div class="w-100 mx-auto save_btn">
                                <button type="submit" class="btn btn-info "><span
                                        class="spinner-grow spinner-grow-sm formloader" style="display: none;"
                                        role="status" aria-hidden="true"></span> {{ __('backend.Save') }}</button>
                                <a href="{{ url('admin/hotels') }}" class="btn btn-default back"><span
                                        class="spinner-grow spinner-grow-sm formloader" style="display: none;"
                                        role="status" aria-hidden="true"></span> {{ __('backend.Back') }}</a>
                            </div>
                        </form>

                        {{-- <-   ------------------------------------------------------------ Inroom Dining Form section ------------------------------------------------------------   -> --}}

                        <form method="POST" id="inroom_dining-form" class="col-md-12 hide" role="form"
                            enctype="multipart/form-data">
                            <input type="hidden" class="form_hotel_id" name="form_hotel_id">
                            <input type="hidden" class="menu_id" name="menu_id">
                            @csrf

                            <div id="config_inroom_form_add" class="mb-2">

                                <div class="row my-1 pt-4 mb-2">
                                    <div class="col-md-12 ml-5 row">
                                        <div class="form-group col-md-12">
                                            <label class="control-label"
                                                for="extra">{{ __("Main Menu Dishes ") }}*</label>
                                        </div>
                                    </div>
                                
                                    <div class="col-md-12 ml-5" id="config_inroom_define_extra">
                                        
                                        <div class="row col-md-12 inroom_extras_row">
                                            <input type="hidden" name="inroom_extras[][id]" >
                                            <input type="hidden" name="inroom_extras[][catg]" value="veg">
                                                                                       
                                            <div class="col-md-3">
                                                <div class="col-md-12 mb-6">
                                                    <div class="form-group extraLabels">
                                                        <div class="input-group">
                                                            <input type="text" name="inroom_extras[][name]" id="config_bf_label"
                                                                class="form-control"
                                                                placeholder="{{ __('Label') }}" autocomplete="off"
                                                                data-parsley-required="true" />
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-3">
                                                <div class="col-md-12 mb-6">
                                                    <div class="form-group extraprice">
                                                        <div class="input-group">
                                                            <input type="text" name="inroom_extras[][price]" id="config_bf_price"
                                                                class="form-control"
                                                                placeholder="{{ __('Price') }}" autocomplete="off"
                                                                data-parsley-required="true" />
                                                        </div>
                                                    </div>
                                                </div>
                                            </div> 
                                        </div>
                                       
                                    </div> 
                                </div>

                            </div>

                            {{-- <div class="w-100 mx-auto save_btn">
                                <button type="submit" class="btn btn-info " id="lunch_dinner_save"><span
                                        class="spinner-grow spinner-grow-sm formloader" style="display: none;"
                                        role="status" aria-hidden="true"></span> {{ __('backend.Save') }}</button>
                                <a href="{{ url('admin/hotels') }}" class="btn btn-default back"><span
                                        class="spinner-grow spinner-grow-sm formloader" style="display: none;"
                                        role="status" aria-hidden="true"></span> {{ __('backend.Back') }}</a>
                            </div> --}}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>

    </div>

    <script src="{{ asset('plugins/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('js/parsley.min.js') }}"></script>
    <script src="{{ asset('plugins/datatables-bs4/js/dataTables.bootstrap4.js') }}"></script>
    
    <script src="{{ asset('plugins/select2/js/select2.full.min.js') }}"></script>

    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.js"></script>

    {{-- deleting a row --}}
    <script>
        function del_breakfast_extra(id) {
            $('.breakfast_extras_row_' + id + '').remove();
            $.ajax({
                url: '{{ url('admin/config_FandB/breakfast/del/extra') }}',
                type: 'DELETE',
                data: {
                    'id': id,
                    _token: '{{ csrf_token() }}'
                },
                success: function(res) {
                    if (res.status === 1) {
                        toastr.success(res.message);
                    } else {
                        toastr.error(res.message);
                    }
                }
            })
        }

        function del_new_breakfast_extra(id) {
            $('.breakfast_extras_row_' + id + '').remove();
        }

        function del_lunch_chef_recommends(id) {
            $('.lunchandDinner_chef_recommend_row_' + id + '').remove();
            $.ajax({
                url: '{{ url('admin/config_FandB/lunch_and_dinner/del/chef_recommend') }}',
                type: 'DELETE',
                data: {
                    'id': id,
                    _token: '{{ csrf_token() }}'
                },
                success: function(res) {
                    if (res.status === 1) {
                        toastr.success(res.message);
                    } else {
                        toastr.error(res.message);
                    }
                }
            })

        };

        function del_new_lunch_chef_recommends(id) {
            $('.lunchandDinner_chef_recommend_row_' + id + '').remove();
        };

        function del_lunch_extra(id) {
            $('.lunchandDinner_extras_row_' + id + '').remove();
            $.ajax({
                url: '{{ url('admin/config_FandB/lunch_and_dinner/del/extra') }}',
                type: 'DELETE',
                data: {
                    'id': id,
                    _token: '{{ csrf_token() }}'
                },
                success: function(res) {
                    if (res.status === 1) {
                        toastr.success(res.message);
                    } else {
                        toastr.error(res.message);
                    }
                }
            })
        }

        function del_new_lunch_extra(id) {
            $('.lunchandDinner_extras_row_' + id + '').remove();
        }

        function del_inroom_extra(id) {
            $('.inroom_extras_row_' + id + '').remove();
            $.ajax({
                url: '{{ url('admin/config_FandB/inroom/del/extra') }}',
                type: 'DELETE',
                data: {
                    'id': id,
                    _token: '{{ csrf_token() }}'
                },
                success: function(res) {
                    if (res.status === 1) {
                        toastr.success(res.message);
                    } else {
                        toastr.error(res.message);
                    }
                }
            })
        }

        function del_new_inroom_extra(id) {
            $('.inroom_extras_row_' + id + '').remove();
        }
    </script>

    {{-- adding a new row --}}
    <script>
        var config_breakfast_extras = "{{ $bfStarterCount }}";

        function add_breakfast_extra(menus) {

            config_breakfast_extras++;
            $.ajax({
                url: '{{ url('admin/config_FandB/breakfast/add_breakfast_extra_row') }}',
                dataType: 'html',
                data: {
                    'row_id': config_breakfast_extras,
                    'data': menus,
                },
                success: function(result) {
                    $('#config_breakfast_define_extra').append(result)
                }
            });
        }

        var config_lunch_chef_recoomend = "{{ $lunchChefCount }}";

        function add_lunch_chef_recommends() {

            config_lunch_chef_recoomend++;
            $.ajax({
                url: '{{ url('admin/config_FandB/lunch_and_dinner/add_lunch_chefRecommend_row') }}',
                dataType: 'html',
                data: {
                    'row_id': config_lunch_chef_recoomend,
                },
                success: function(result) {
                    $('#chef-recommends').append(result)
                }
            });
        }

        var config_lunch_extra = "{{ $lunchStarterCount }}";

        function add_lunch_extras(menus) {

            config_lunch_extra++;
            $.ajax({
                url: '{{ url('admin/config_FandB/lunch_and_dinner/add_lunch_extras_row') }}',
                dataType: 'html',
                data: {
                    'data': menus,
                    'row_id': config_lunch_extra,
                },
                success: function(result) {
                    $('#lunch_extras').append(result)
                }
            });
        }

        var config_inroom_extra = "{{ $inroomStarterCount }}";

        function add_inroom_extra_row(menus) {

            config_inroom_extra++;
            $.ajax({
                url: '{{ url('admin/config_FandB/inRoom_dining/add_inroom_extras_row') }}',
                dataType: 'html',
                data: {
                    'data': menus,
                    'row_id': config_inroom_extra,
                },
                success: function(result) {
                    $('#config_inroom_define_extra').append(result)
                }
            });
        }
    </script>

    <script>
        $(document).ready(function() {

            $(document).on('change', '#hotelname', function() {

                var hotel_id = $(this).val();
                $('.form_hotel_id').val(hotel_id);

                $('#restaurant_dropdown').addClass('hide');

                $.ajax({
                    url: '{{ url('admin/config_FandB/lunch_and_dinner/restaurants') }}',
                    data: {
                        'id': hotel_id
                    },
                    type: 'get',
                    success: function(data) {
                        var restaurant = data.restaurants;
                        var newoption = "";

                        //    console.log(restaurant);
                        newoption +=
                            `<option value="" selected disabled>{{ __('Select Restaurant') }}</option>`;
                        restaurant.forEach(e => {
                            newoption +=
                                `<option value=${e.id}>${e.lunchhotelname}</option>`;
                            $('#dropdown_restaurant').html(newoption);
                        });
                    }
                });

                var catg = $(this).parent().parent();
                var categroies = " ";
                categroies += `
                                <option value="0" selected>{{ __('Select Category') }}</option>
                                <option value="breakfast">{{ __('Breakfast') }}</option>
                                <option value="lunch_dinner" >{{ __('Lunch And Dinner') }}</option>
                                <option value="inroom_dining" >{{ __('InRoom Dining') }}</option>`;

                catg.find('#food_category').html(" ");
                catg.find('#food_category').append(categroies);
                $('#config_breakfast_form_add').html(" ");
                $('#chef-recommends').html(" ");
                $('#config_lunch_form_add').html(" ");
                $('#config_inroom_form_add').html(" ");
                $('#dropdown_extras').html("<option selected disabled>{{ __('Select Menu') }}</option>");
            });

            // <---    -------------------------------------\\\\\\\\ On change of food_category  section ///////---------------------------------    ---->

            $(document).on('change', '#food_category', function() {
                var hotel_id = $(this).parent().siblings().find("#hotelname").val();
                 
                var catg_id = $(this).val();
                var formId = $(this).parent().parent().siblings();

                // <----    -------------------------------------- To Show Data in Breakfast forms ---------------------------------------------    ---->

                if (catg_id == 'breakfast') {
                    formId.find('#breakfast-form').removeClass('hide');
                    formId.find('#lunch-form').addClass('hide');
                    formId.find('#inroom_dining-form').addClass('hide');
                    $('#restaurant_dropdown').addClass('hide');

                    $.ajax({
                        url: '{{ url('admin/config_FandB/breakfast/menu') }}',
                        data: {
                            'id': hotel_id
                        },
                        type: 'get',
                        success: function(data) {
                            var menu = data.menus;
                            var newoption = ""; 
                            var youMayLikeIt = ""; 

                            if(menu.length > 0){
                            newoption +=  `<option value="" selected disabled>{{ __('Select Menu') }}</option>`;
                                menu.forEach(e => {
                                    newoption += `<option value=${e.id}>${e.breakfastmenuname}</option>`;
                                    $('#dropdown_extras').html(newoption);
                                });
                            }
                            else{
                                newoption += `<option disabled selected>No Option Available</option>`;
                                $('#dropdown_extras').html(newoption);
                            }
                            

                            youMayLikeIt+= `<div class="row col-md-12 breakfast_youMayLikeIt_row_1 ">
                                                <input type="hidden" name="breakfast_youMayLike[1][id]" value="1 ">
                                                <div class="col-md-3 align-self-center">
            <select name="hotelname" id="hotelname" class="form-control " data-placeholder="{{ __('Select HOtel') }}"
                data-dropdown-css-class="select2-primary">
                <option selected disabled>{{ __('Select Hotel') }}</option>
                @foreach ($hotels as $hotel)
                    <option value="{{ $hotel->id }}">{{ $hotel->hotelname }}</option>
                @endforeach
            </select>
        </div>
                                                
                                                  
                                            </div>`;
                            $('#breakfastYouMayLikeIt').html(youMayLikeIt);

                        }
                    });

                }

                // <----    ------------------------------------ To Show Data in Lunch and Dinner forms ----------------------------------------    ---->
                else if (catg_id == "lunch_dinner") {

                    formId.find('#breakfast-form').addClass('hide');
                    formId.find('#lunch-form').removeClass('hide');
                    formId.find('#inroom_dining-form').addClass('hide');
                    $('#restaurant_dropdown').removeClass('hide');

                }

                // <----    ------------------------------------ To Show Data in InRoom Dining forms -------------------------------------------    ---->
                
                else if (catg_id == "inroom_dining") {
                    formId.find('#lunch-form').addClass('hide');
                    formId.find('#breakfast-form').addClass('hide');
                    formId.find('#inroom_dining-form').removeClass('hide');
                    $('#restaurant_dropdown').addClass('hide');

                    $.ajax({
                        url: '{{ url('admin/config_FandB/inRoom_dining/menu') }}',
                        data: {
                            'id': hotel_id
                        },
                        type: 'get',
                        success: function(data) {
                            var menu = data.menus;
                            var newoption = "";

                            // console.log(menu);

                            if(menu.length > 0){
                            newoption +=  `<option value="" selected disabled>{{ __('Select Menu') }}</option>`;
                                menu.forEach(e => {
                                    newoption += `<option value=${e.id}>${e.inroommenuname}</option>`;
                                    $('#dropdown_extras').html(newoption);
                                });
                            }
                            else{
                                newoption += `<option disabled selected>No Option Available</option>`;
                                $('#dropdown_extras').html(newoption);
                            }
                        }
                    });

                }

                $('#config_breakfast_form_add').html(" ");
                $('#chef-recommends').html(" ");
                $('#config_lunch_form_add').html(" ");
                $('#config_inroom_form_add').html(" ");
                $('#dropdown_extras').html("<option selected disabled>{{ __('Select Menu') }}</option>");
                $('#dropdown_restaurant option:eq(0)').prop('disabled',"true");
                $('#dropdown_restaurant option:eq(0)').prop('selected', "selected");
            });
           
                                                         // restaurant dropdown of lunch and dinner function 

            $(document).on('change', '#dropdown_restaurant', function() {
                var lunchListId = $(this).val();
                $('.lunch_list_id').val(lunchListId);
 
                $.ajax({
                    url: '{{ url('admin/config_FandB/lunch_and_dinner/menu') }}',
                    data: {
                        'id': lunchListId
                    },
                    type: 'get',
                    success: function(data) {
                        var chefRecomm = data.chefRecommendData;
                        var menu = data.menus;
                        var chefrows = "";
                        var incrChefValue = 0;
                        var newoption = "";

                        // console.log(chefRecomm.length);

                        if(chefRecomm.length > 0){
                        chefRecomm.forEach(e => {
                            incrChefValue++;

                            chefrows += `<div class="row col-md-12 lunchandDinner_chef_recommend_row_`+e.id+` ">
                                                <input type="hidden" name="lunch_chef_recommend[`+incrChefValue+`][id]" value="`+e.id+` ">
                                                <div class="col-md-5">
                                                    <div class="col-md-12 mb-6">
                                                        <div class="form-group">
                                                            <div class="input-group">
                                                                <div class="image_preview" id="image_preview">
                                                                    <img height="50" width="50" id="previewing0" src="`+e.itemimage+`" >
                                                                </div>
                                                                <input type="file" id="file"
                                                                    name="lunch_chef_recommend[`+incrChefValue+`][image]" class="form-control">
                                                                <input type="hidden" name="lunch_chef_recommend[`+incrChefValue+`][image]"
                                                                    value="`+e.itemimage+`" />
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-5">
                                                    <div class="col-md-12 mb-6">
                                                        <div class="form-group extraLabels">
                                                            <div class="input-group">
                                                                <input type="text" name="lunch_chef_recommend[`+incrChefValue+`][name]"
                                                                    id="extra" class="form-control" value="`+e.itemname+`"
                                                                    placeholder="{{ __('Label Here') }}" autocomplete="off"
                                                                    data-parsley-required="true" />
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-1">
                                                    <a onclick="del_lunch_chef_recommends(`+e.id+`)" class="btn btn-danger btn-xs"
                                                        style="color:white;"><i class="fa fa-trash"></i></a>
                                                </div>
                                            </div> `;
                            $('#chef-recommends').html(chefrows);
                        }); }
                        else{
                            $('#chef-recommends').html("");
                        }
                       
                        if(menu.length > 0){
                            newoption +=  `<option value="" selected disabled>{{ __('Select Menu') }}</option>`;
                                menu.forEach(e => {
                                    newoption += `<option value=${e.id}>${e.menuname}</option>`;
                                    $('#dropdown_extras').html(newoption);
                                });
                            }
                            else{
                                newoption += `<option disabled selected>No Option Available</option>`;
                                $('#dropdown_extras').html(newoption);
                            }

                        $('#config_lunch_form_add').html(" ")
                    }
                });
            });

                                                                          // extra's dropdown function here   

            $(document).on('change', '#dropdown_extras', function() {
                var menuid = $(this).val();
                var foodCatg = $('#food_category').val();
                $('.menu_id').val(menuid);

                // console.log(foodCatg);

                if (foodCatg == 'breakfast') {
                    $.ajax({
                        url: '{{ url('admin/config_FandB/breakfast') }}',
                        dataType: 'html',
                        data: {
                            'id': menuid,
                        },
                        success: function(result) {
                            $('#config_breakfast_form_add').html(result)
                        }
                    });
                } 
                
                else if (foodCatg == "lunch_dinner") {
                    $.ajax({
                        url: '{{ url('admin/config_FandB/lunch_and_dinner') }}',
                        dataType: 'html',
                        data: {
                            'id': menuid,
                        },
                        success: function(result) {
                            $('#config_lunch_form_add').html(result)
                        }
                    });
                } 
                
                else if (foodCatg == "inroom_dining") {
                    $.ajax({
                        url: '{{ url('admin/config_FandB/inRoom_dining') }}',
                        dataType: 'html',
                        data: {
                            'id': menuid,
                        },
                        success: function(result) {
                            $('#config_inroom_form_add').html(result)
                        }
                    });
                }
            });

            // show hide you may like it and  chef recommend data 

            
            var a = 0;
            showHide = function(){
                 if( a == 0){
                     $('.groupHideShow').hide();
                     $('.downArrow').removeClass('hide');
                     $('.upArrow').addClass('hide');
                     a = 1;
                    }
                    else{
                        $('.groupHideShow').show();
                        $('.downArrow').addClass('hide');
                     $('.upArrow').removeClass('hide');
                     a = 0;
                 } 
                };

            // <---    ---------------------------------- Breakfast onsubmit button action -------------------------------------------------    ---->

            $("#breakfast-form").on('submit', function(e) {
                e.preventDefault();
                var _this = $(this);
                var formData = new FormData(this);
                formData.append('_method', 'post');
                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                });
                $.ajax({
                    url: '{{ url('admin/config_FandB/breakfast_submit') }}',
                    dataType: 'json',
                    data: formData,
                    type: 'POST',
                    cache: false,
                    contentType: false,
                    processData: false,
                    beforeSend: function() {
                        before(_this)
                    },
                    // hides the loader after completion of request, whether successfull or failor.
                    complete: function() {
                        complete(_this)
                    },
                    success: function(res) {
                        if (res.status === 1) {
                            toastr.success(res.message);
                            window.location.href = "{{ url('admin/config_FandB') }}"
                        } else {
                            toastr.error(res.message);
                        }
                    },
                    error: function(jqXHR, textStatus, textStatus) {
                        if (jqXHR.responseJSON.errors) {
                            $.each(jqXHR.responseJSON.errors, function(index, value) {
                                toastr.error(value)
                            });
                        } else {
                            toastr.error(jqXHR.responseJSON.message)
                        }
                    }
                });
                return false;
            });

            // <---    -------------------------------------- Lunch onsubmit button action -------------------------------------------------    ---->

            $("#lunch-form").on('submit', function(e) {
                e.preventDefault();
                var _this = $(this);
                var formData = new FormData(this);
                formData.append('_method', 'post');
                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                });
                $.ajax({
                    url: '{{ url('admin/config_FandB/lunchandDinner_submit') }}',
                    dataType: 'json',
                    data: formData,
                    type: 'POST',
                    cache: false,
                    contentType: false,
                    processData: false,
                    beforeSend: function() {
                        before(_this)
                    },
                    // hides the loader after completion of request, whether successfull or failor.
                    complete: function() {
                        complete(_this)
                    },
                    success: function(res) {
                        if (res.status === 1) {
                            toastr.success(res.message);
                            window.location.href = "{{ url('admin/config_FandB') }}"
                            // $('#edit_attribute').parsley().reset();
                            // window.location.reload();
                        } else {
                            toastr.error(res.message);
                        }
                    },
                    error: function(jqXHR, textStatus, textStatus) {
                        if (jqXHR.responseJSON.errors) {
                            $.each(jqXHR.responseJSON.errors, function(index, value) {
                                toastr.error(value)
                            });
                        } else {
                            toastr.error(jqXHR.responseJSON.message)
                        }
                    }
                });
                return false;
            });

            // <---    ------------------------------------- InRoomDining onsubmit button section ------------------------------------------    ---->

            $("#inroom_dining-form").on('submit', function(e) {
                e.preventDefault();
                var _this = $(this);
                var formData = new FormData(this);
                formData.append('_method', 'post');
                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                });
                $.ajax({
                    url: '{{ url('admin/config_FandB/inroom_submit') }}',
                    dataType: 'json',
                    data: formData,
                    type: 'POST',
                    cache: false,
                    contentType: false,
                    processData: false,
                    beforeSend: function() {
                        before(_this)
                    },
                    // hides the loader after completion of request, whether successfull or failor.
                    complete: function() {
                        complete(_this)
                    },
                    success: function(res) {
                        if (res.status === 1) {
                            toastr.success(res.message);
                            window.location.href = "{{ url('admin/config_FandB') }}"
                        } else {
                            toastr.error(res.message);
                        }
                    },
                    error: function(jqXHR, textStatus, textStatus) {
                        if (jqXHR.responseJSON.errors) {
                            $.each(jqXHR.responseJSON.errors, function(index, value) {
                                toastr.error(value)
                            });
                        } else {
                            toastr.error(jqXHR.responseJSON.message)
                        }
                    }
                });
                return false;
            });

            // <---    ------------------------------------- InRoomDining onsubmit button section ------------------------------------------    ---->

        });
    </script>
@endsection

## Context (Environment)

- write your environment
laravel v7

i am trying to format the document but getting an error of too lengthy file 
## Description

Any other informations

**Comment by bilogic** [comment]
Could it be related to #500?

**Comment by shufo** [comment]
@bilogic 
Partially related, but this seems other cause. 

It seems `@foreach` directive in the js expression preventing formatting.

```js
youMayLikeIt+= `<div class="row col-md-12 breakfast_youMayLikeIt_row_1 ">
                                            <input type="hidden" name="breakfast_youMayLike[1][id]" value="1 ">
                                            <div class="col-md-3 align-self-center">
        <select name="hotelname" id="hotelname" class="form-control " data-placeholder="{{ __('Select HOtel') }}"
            data-dropdown-css-class="select2-primary">
            <option selected disabled>{{ __('Select Hotel') }}</option>
            @foreach ($hotels as $hotel)
                <option value="{{ $hotel->id }}">{{ $hotel->hotelname }}</option>
            @endforeach
        </select>
    </div>
                                            
                                              
                                        </div>`;
```

Please try extract `@foreach` directive outside JS expression as a workaround like

```blade
<script>
@foreach ($hotels as $hotel)
  // js expression
  const template = `{{ $hotel }}`;
@endforeach
</script>
```

**Comment by GoodM4ven** [comment]
Moreover, Blade created [anonymous](https://laravel.com/docs/9.x/blade#anonymous-components) [components](https://laravel.com/docs/9.x/blade#components) for a reason. Please use them with repeated code.

Also, keeping the scripts in the same file, instead of extracting them to their own, will ruin the view's code in production, and will make it easier - in a sense - to spot vulnerabilities by 3rd parties.
