### ISSUE TITLE
elseif format

### ISSUE THREAD

**Issue by adrianvengeance** [shufo/vscode-blade-formatter#536]
## I want to write like this
`@if (session()->has('success'))`
//do something
`@elseif (session()->has('error'))`
//do something
`@endif`
## but the formatter did this
![image](https://user-images.githubusercontent.com/67651472/185982624-aa4c8758-1df3-480e-ba1a-e34a2be78de1.png)

![Screenshot 2022-08-23 at 00-45-20 🧨 syntax error unexpected ' ' expecting '(' (View C _xampp_htdocs_be-donasi_resources_views_layouts_app blade php)](https://user-images.githubusercontent.com/67651472/185986343-db0cf2dd-80b3-49c0-a9ae-b8a4581002a1.png)

## Context (Environment)
Laravel blade formatter v0.17.1

**Comment by shufo** [comment]
It looks this happens when elseif statement exists in script block. (outside script block is ok)
I'll look into it.

**Comment by shufo** [comment]
Fixed at https://github.com/shufo/vscode-blade-formatter/releases/tag/v0.17.3
