### ISSUE TITLE
Issue while Formating Blade

### ISSUE THREAD

**Issue by rajeshkumarjha1** [shufo/vscode-blade-formatter#537]
## Template

**Please write your blade template that occurs issues.**

## Context (Environment)

- Windows VS CODE, LARAVEL 8 , Blade Template

- It give error while formatting blade like cannot format.

Any other informations

**Comment by clementmas** [comment]
You need to provide more information. See https://github.com/shufo/vscode-blade-formatter/issues/372

**Comment by shufo** [comment]
Closed by #372
