### ISSUE TITLE
Issue with nullsafe operator v0.17.4

### ISSUE THREAD

**Issue by CoffeeKing68** [shufo/vscode-blade-formatter#544]
## Template

**Please write your blade template that occurs issues.**
```blade
{{-- WORKS --}}
<div>{{ $user?->post->name }}</div>
<div>{{ $record->learner->currentEnrollment->class->grade?->code }}</div>
<div>{{ $record->learner->currentEnrollment->class?->grade->code }}</div>
{{-- missing row --}}
<div>{{ $record->learner?->currentEnrollment->class->grade->code }}</div>
<div>{{ $record?->learner->currentEnrollment->class->grade->code }}</div>

{{-- FAILS --}}
<x-generator.table.cell>{{ $record->learner->currentEnrollment?->class->grade->code }}</x-generator.table.cell>
<div>{{ $record->learner->currentEnrollment?->class->grade->code }}</div>
<div>{{ $record->learner?->class->grade->code }}</div>
```

## Context (Environment)
```json
{
"[blade]": {
        "editor.defaultFormatter": "shufo.vscode-blade-formatter",
        "editor.autoClosingBrackets": "always"
    },
}
```
VERSION: 0.17.4 (Last updated: 03/09/2022, 21:01:52)

Any line under `{{-- FAILS --}}` causes the following Parse Error:

`Parse Error : syntax error, unexpected 'class' (T_CLASS) on line 1 > 1 | <?php echo $record->learner->currentEnrollment?->class->grade->code ?> | ^`

I tried to narrow down what causes the issue, all the lines under the `{{-- WORKS --}}` comment doesn't cause the issue.

All I know is that the issue occurs only when the null safe operator but only when it is before exactly 3 `->` operators?

Thanks

**Comment by shufo** [comment]
@CoffeeKing68 
Thanks for reporting the issue. 

It seems [php-parser](https://github.com/glayzzle/php-parser) used in this extension recognized `class` property as class statement.
For temporary workaround, please use  unreserved word for identifier after nullsafe operator.

e.g.
 
```blade
<div>{{ $record->learner->currentEnrollment?->_class->grade->code }}</div>
```

I'll add an option to disable PHP syntax checking in a future release, so the name change may not be necessary then.

**Comment by CoffeeKing68** [comment]
Ah I see, I did not consider that. I appreciate your work on this. Will keep an eye out for the update.

Thanks
