### ISSUE TITLE
Incorrectly strips leading slash from use statement in @php block

### ISSUE THREAD

**Issue by PatrickSJ** [shufo/vscode-blade-formatter#546]
## Template
```
@php
        use \Carbon\CarbonInterval;

        CarbonInterval::setCascadeFactors([
            'minute' => [60, 'seconds'],
            'hour' => [60, 'minutes'],
        ]);
@endphp

{{ CarbonInterval::minutes($some_value)->cascade()->format('%H:%I') }}

```

## Context (Environment)
VS Code Version: 1.71.0
vscode-blade-formatter v0.17.4

## Description
Given `use \Carbon\CarbonInterval;` the formatter removes the leading slash resulting it being incorrectly formatted to `use Carbon\CarbonInterval;`  This causes errors such as `Class "Illuminate\Support\Carbon\CarbonInterval" `not found.

**Comment by shufo** [comment]
It seems prettier/plugin-php used in this extension trims leading slash of `use \Carbon\CarbonInterval`.

For workaround, try use full qualified class instead of use statement.

```php
\Carbon\CarbonInterval::setCascadeFactors([
    'minute' => [60, 'seconds'],
    'hour' => [60, 'minutes'],
]);
```
