### ISSUE TITLE
Cannot automatically sort tailwindcss classes

### ISSUE THREAD

**Issue by jedymatt** [shufo/vscode-blade-formatter#548]
## Cannot automatically sort tailwindcss classes

**Please write your blade template that occurs issues.**

I tried settings  `sortTailwindcssClasses` to `true` in both rc file and vscode settings.json but it does not sort the tailwindcss classes

## Context (Environment)

- tailwindcss@3.1.8
- Laravel Version 9.28.0

## Description

My config file

*.bladeformatterrc.json*
```json
{
    "wrapAttributes": "force-expand-multiline",
    "sortHtmlAttributes": "code-guide",
    "endWithNewLine": true,
    "noMultipleEmptyLines": true,
    "sortTailwindcssClasses": true
}
```
Before formatting
```blade
<div>
    <div class="flex flex-row items-baseline justify-center gap-4">
        <span class="block">Select Event</span>
        <div class="flex-grow">@livewire('admin.select-event')</div>
    </div>
</div>
```

After formatting
```blade
<div>
    <div class="flex flex-row items-baseline justify-center gap-4">
        <span class="block">Select Event</span>
        <div class="flex-grow">@livewire('admin.select-event')</div>
    </div>
</div>
```

The `gap-4` class should be after `flex-row`

**Comment by shufo** [comment]
Hi @jedymatt 
It seems classes are already sorted.

When I formatted below

```html
<div>
    <div class="gap-4 justify-center flex flex-row items-baseline ">
        <span class="block">Select Event</span>
        <div class="flex-grow">@livewire('admin.select-event')</div>
    </div>
</div>
```

it will be formatted into 

```html
<div>
    <div class="flex flex-row items-baseline justify-center gap-4">
        <span class="block">Select Event</span>
        <div class="flex-grow">@livewire('admin.select-event')</div>
    </div>
</div>
```

This behaviour is compatible with official [tailwind prettier plugin](https://github.com/tailwindlabs/prettier-plugin-tailwindcss).

**Comment by jedymatt** [comment]
My bad, I thought it sorts alphabetically

**Comment by jedymatt** [comment]
Thanks for the response
