### ISSUE TITLE
formatter inserts new line character to normal inner html texts. 

### ISSUE THREAD

**Issue by zemichael-addweb** [shufo/vscode-blade-formatter#559]
## Template

All blade templates

## Context (Environment)

formatter inserts new line character based on the wrap line length to normal inner html texts. 

- write your environment

Please add the feature to add formatting to tags but not to normal texts.

## Description

Please add the feature to add formatting to tags but not to normal texts.

**Comment by shufo** [comment]
@zemichael-addweb 
>formatter inserts new line character based on the wrap line length to normal inner html texts.

Can you post example template?
