### ISSUE TITLE
Error if there are comments inside @php

### ISSUE THREAD

**Issue by adriallongarriu** [shufo/vscode-blade-formatter#563]
## Template
```blade
@php
    // if breadcrumbs aren't defined in the CrudController, use the default breadcrumbs
    $breadcrumbs = $breadcrumbs ?? $defaultBreadcrumbs;
@endphp
```
## Context (Environment)

When you format the code the process start but seems to enter in an endless loop and don't stops. 
I need to close Visual Studio Code.
If i delete the comment the code si formated correctly.

## Description

Any other informations

**Comment by shufo** [comment]
Thanks for reporting the issue @adriallongarriu
I'll look into it.

**Comment by shufo** [comment]
This fix will be included in the next release

**Comment by shufo** [comment]
Fixed at https://github.com/shufo/vscode-blade-formatter/releases/tag/v0.18.1
