### ISSUE TITLE
breaking a string, within {!! !!} ?

### ISSUE THREAD

**Issue by interludic** [shufo/vscode-blade-formatter#57]
## Template
This line gets changed too
`{!! (!empty($response['id'])) ? '<br /><small><a href="'.route('managers.responses.show',[$response['id']]).'">'.$response['id'].'</a></small>' : null !!}`

this
`		 {!! (!empty($response['id'])) ? '<br /><small><a
					href="'.route('managers.responses.show', [$response['id']]).'">'.$response['id'].'</a></small>' :
			null !!} `

**Comment by interludic** [comment]
Basically it tab breaks after the <a tag opens

**Comment by shufo** [comment]
Thanks for creating the issue.
It seems same to me.

```blade
{!! (!empty($response['id'])) ? '<br /><small><a href="'.route('managers.responses.show',[$response['id']]).'">'.$response['id'].'</a></small>' : null !!}
```

```blade
{!! (!empty($response['id'])) ? '<br /><small><a href="'.route('managers.responses.show', [$response['id']]).'">'.$response['id'].'</a></small>' : null !!}
```

Are there any control characters or other differences?
