### ISSUE TITLE
Indentation within @if block etc..

### ISSUE THREAD

**Issue by interludic** [shufo/vscode-blade-formatter#58]
if there a way to have indendation within if blocks etc?

`@if
       line
@endif`

![image](https://user-images.githubusercontent.com/6327261/106537235-0cb56100-654e-11eb-8a99-a4a3ca15b0ec.png)

tab the content within the blocks?

**Comment by shufo** [comment]
seems correctly formatted in my environment with provided input.

```blade
@if(!empty($response['contact']))
<small>{{$response['contact']}}</small>
@endif
```

will formatted into

```blade
@if (!empty($response['contact']))
    <small>{{ $response['contact'] }}</small>
@endif
```

## Environment
- OS: Linux
- vscode-blade-formatter: 0.7.7

I've been confirming that some context lose indentation like directive in script or tag close issue. can you provide context that this input belongs to? thanks.
