### ISSUE TITLE
BLADE Formatter fails when @props([ ... ]) inserted into a component 

### ISSUE THREAD

**Issue by blehner** [shufo/vscode-blade-formatter#593]
## Template

**Please write your blade template that occurs issues.**

## Context (Environment)

Blade formatter does it's job and formats the blade component as usal until i insert the @props([ ...  ]) property. Then the formatter fails and nothing happens but i get an error message.

- write your environment

Environment: Fedora Linux 36 - VS Code 

## Description

Any other informations

**Comment by shufo** [comment]
@blehner 
Can you post the example template? Thanks.
