### ISSUE TITLE
[Feature Suggestion] Add command to format the file manually

### ISSUE THREAD

**Issue by amaelftah** [shufo/vscode-blade-formatter#60]
i would suggest a command that formats the file . as sometimes i want to save the file without formatting 

something like headwind extension can be useful https://github.com/heybourn/headwind/blob/master/src/extension.ts#L37

as i bind the command to keys and i run the formatter when i need

![Screenshot from 2021-02-04 17-57-05](https://user-images.githubusercontent.com/17250137/106919019-69617900-6712-11eb-993c-0e0938c730ba.png)

my vscode key bindings

![Screenshot from 2021-02-04 17-58-06](https://user-images.githubusercontent.com/17250137/106919175-90b84600-6712-11eb-9ef7-485049241141.png)

**Comment by shufo** [comment]
Sorry for the late reply.

I've been busy to fixing bugs so I didn’t get around to implement new feature.

Will be include next release!

**Comment by shufo** [comment]
Added Manual format command at https://github.com/shufo/vscode-blade-formatter/releases/tag/v0.16.0

You can run format by setting Keybinding to `Blade: Format Document`

![image](https://user-images.githubusercontent.com/1641039/175974276-fbf806ab-33bb-4065-b1f4-e96f560117ed.png)
