### ISSUE TITLE
PHP 8: the null safe operator

### ISSUE THREAD

**Issue by vlademirjunior** [shufo/vscode-blade-formatter#61]
Parse Error : syntax error, unexpected '->' (T_OBJECT_OPERATOR) on line 1 > 1 | <?php old('title', $video?->title) ?> | ^

Issue: Should be able use null safe operator.

**Comment by shufo** [comment]
Seems upstream dependency is not yet supported php 8. 
https://github.com/prettier/plugin-php/issues/1599

**Comment by shufo** [comment]
Just released [v0.7.4](https://marketplace.visualstudio.com/items?itemName=shufo.vscode-blade-formatter) with null safe operator support.
