### ISSUE TITLE
command 'vscode-blade-formatter.format' not found

### ISSUE THREAD

**Issue by gaetan-hexadog** [shufo/vscode-blade-formatter#610]
Hello,

I just installed the plugin from VSCode Extensions library but it doesn't work.

If I try to run it by command panel (Blade: Format Document) I get the following error message.

```
Command 'Blade: Format Document' resulted in an error (command 'vscode-blade-formatter.format' not found)
```

Can you please help?

**Comment by shufo** [comment]
Seems the command registered with this extension was not found.
It may be that the command fails to register at startup, but I don't know the case where it fails to register a command. 
I'll look into it.

**Comment by furopi** [comment]
<img width="419" alt="2022-12-02" src="https://user-images.githubusercontent.com/36579099/205248784-ac85f476-0ca7-4098-8e74-40a78e2079e2.png">

**Comment by furopi** [comment]
Is this problem still not fixed yet? 😢😥
