### ISSUE TITLE
matchVariant is not a function

### ISSUE THREAD

**Issue by nathangross** [shufo/vscode-blade-formatter#622]
## Template

Any blade file that has any class attribute

## Context (Environment)

Laravel 9 + tailwindcss (3.2.4) via VS Code

Tailwind Config
`
content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
    ],
`
... 

`
    plugins: [
        require("tailwind-scrollbar-hide"),
        require("@tailwindcss/typography"),
        require("@tailwindcss/aspect-ratio"),
        require("tailwindcss-safe-area"),
        require("@tailwindcss/forms"),
        require("@tailwindcss/container-queries"),
    ],
`

When I save any blade file that has any class attributes on any html element, I get the error: matchVariant is not a function. 

This seems to only happen when I have the tailwind container-queries plugin active. If I comment that file out, the error seems to go away. 

I assume this is an issue with tailwind, but the error in VS code suggests that it's related to this blade formatter plugin.

Any ideas on how to stop this error?

Thanks!

**Comment by nathangross** [comment]
@shufo Curious if you've been able to look at this one and/or reproduce it. Thanks!

**Comment by nathangross** [comment]
Looks like something that was added in Tailwind 3.2:

https://github.com/tailwindlabs/tailwindcss/discussions/9574#parameterized-variants-with-match-variant

**Comment by shufo** [comment]
@nathangross 
Thanks for the information! Also reproduced in my environment when I upgraded to tailwind ^3.2.
I'll have a closer look at what's going on here.

**Comment by nathangross** [comment]
Sounds good. I'll be keeping an eye out for an update. Thanks!!

**Comment by shufo** [comment]
@nathangross 
[Fixed](https://github.com/shufo/tailwindcss-class-sorter/commit/8c08b53727a8ad32ca1bc7ff86b538107d24d27f) tailwind class sorting feature to support tailwind 3.2 and released https://github.com/shufo/vscode-blade-formatter/releases/tag/v0.20.8.
Please try the latest version!

**Comment by nathangross** [comment]
Seems to work great! Thanks for the update! I'll close this out :)
