### ISSUE TITLE
laravel named slots causing the closing tag add a indent tab

### ISSUE THREAD

**Issue by Fanreza** [shufo/vscode-blade-formatter#633]
## Template

```blade
<x-slot:tbody>
        // some html
        </x-slot>
```

## Context (Environment)

Windows 10
Laravel 9
Vscode 1.73.1
Laravel Blade formatter v0.20.3

```json
{
    "indentSize": 4,
    "wrapAttributes": "auto",
    "wrapLineLength": 120,
    "endWithNewLine": true,
    "noMultipleEmptyLines": false,
    "useTabs": false,
    "sortHtmlAttributes": "none",
    "noPhpSyntaxCheck": false
}
```

## Description

it should be
```blade
<x-slot:tbody>
        // some html
</x-slot>
```

more better html tag position

**Comment by shufo** [comment]
Thanks for reporting the issue @Fanreza 

This is because the html parser used in this extension parses as this tag is not matched. 
To work around this, you can write 

```html
<x-slot:tbody>
    // some html
</x-slot:tbody>
```

**Comment by Fanreza** [comment]
Thanks for the example, I close this issue

**Comment by LichtAnd** [comment]
> Thanks for reporting the issue @Fanreza
> 
> This is because the html parser used in this extension parses as this tag is not matched. To work around this, you can write
> 
> ```
> <x-slot:tbody>
>     // some html
> </x-slot:tbody>
> ```

This behaviour almost made me stop using this otherwise very helpfull extension. Finding this issue and workaround saved my day. Maybe add a hint to the readme or the extension description?
