### ISSUE TITLE
Livewire using blade tags adds a trailing comma after formatting that breaks the app

### ISSUE THREAD

**Issue by devsquad-eduardo-barijan** [shufo/vscode-blade-formatter#643]
## Template

**Please write your blade template that occurs issues.**

```
@livewire(
        $block['path'],
        [
            'componentSettings' => $block['properties'],
            'componentKey'      => $block['key'],
            'site'              => $site ?? null,
            'post'              => $post ?? null,
            'theme'             => $theme,
            'editing'           => false,
            'preview'           => $preview,
        ],
        key($key)
    )
```

## When rendering Livewire components using the blade syntax `@livewire` the formatter is adding a trailing comma, and it breaks the application rendering:

```
@livewire(
      $block['path'],
      [
          'componentSettings' => $block['properties'],
          'componentKey' => $block['key'],
          'site' => $site ?? null,
          'post' => $post ?? null,
          'theme' => $theme,
          'editing' => false,
          'preview' => $preview,
      ],
      key($key), <-- here
  )
```

- Windows 10
- Inside WSL 2 running Arch
- VSCode 1.74.0
- Extension v. 0.20.3

## In this case it should not add the trailing comma

I am pretty sure this is due to the array being inserted as an argument to the blade syntax, but as Livewire inside loops needs to be keyed, we need to provide it as such. It should simple ignore inside the blade syntax and not add the comma at all.

Any other informations:

- as it stands now, when there is such syntax present for Livewire rendering, we need to disable the auto-save entirely for the particular blade file..

**Comment by shufo** [comment]
Fixed at https://github.com/shufo/vscode-blade-formatter/releases/tag/v0.20.6
