### ISSUE TITLE
laravel twill cms blade @formField with array data indent incorrect

### ISSUE THREAD

**Issue by petertsoisstuff** [shufo/vscode-blade-formatter#647]
## Template
What I got
```blade
@formField('input', [
'name' => 'page_title',
'label' => 'Page title',
'maxlength' => 200
])
```

I expceted
```blade
@formField('input', [
    'name' => 'page_title',
    'label' => 'Page title',
    'maxlength' => 200
])
```

## Context (Environment)

- php7.4
- laravel 6.2
- twill 2.5
[( https://twill.io/docs/form-fields/input.htm)](https://twill.io/docs/form-fields/input.html)

**Comment by shufo** [comment]
Released https://github.com/shufo/vscode-blade-formatter/releases/tag/v0.20.6 with this fix.
