### ISSUE TITLE
infinity additional indent

### ISSUE THREAD

**Issue by iampelixm** [shufo/vscode-blade-formatter#65]
Issue Type: <b>Bug</b>

<script>
var some_var=`
any code`;
</script>

lines inside `` gettings additional indent on each time formatter works

Extension version: 0.7.0
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 20.2.0
Remote OS version: Linux x64 5.4.0-65-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id 3414b515-e95d-4306-b3d4-a813d35c283b|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.7.252|
|OS|Linux x64 5.4.0-65-generic|
|CPUs|Intel(R) Xeon(R) CPU           E5640  @ 2.67GHz (1 x 2666)|
|Memory (System)|2.92GB (0.30GB free)|
|VM|100%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by shufo** [comment]
Hi @iampelixm 
This issue is now fixed above https://github.com/shufo/vscode-blade-formatter/releases/tag/v0.7.17. please upgrade it.
