### ISSUE TITLE
cant format blade files

### ISSUE THREAD

**Issue by sohailtahir5858** [shufo/vscode-blade-formatter#653]
## Template

**Please write your blade template that occurs issues.**

## Context (Environment)

- write your environment

## Description

Any other informations

**Comment by jpgerber1986** [comment]
I'm getting this as well - here's the portion it's erroring on:

 <@php
    if (count($contacts)): 
@endphp //ERROR IS HERE
<?php foreach ($contacts as $id => $contact): ?>
<tr>
    <th scope="row">1</th>
    <td>{{ $contact['name'] }}</td>
    <td>{{ $contact['phone'] }}</td>
    <td>alfred@test.com</td>
    <td>Company one</td>
    <td width="150">
        <a href="{{ route('contacts.show', $id) }}"
            class="btn btn-sm btn-circle btn-outline-info" title="Show"><i
                class="fa fa-eye"></i></a>
        <a href="form.html" class="btn btn-sm btn-circle btn-outline-secondary"
            title="Edit"><i class="fa fa-edit"></i></a>
        <a href="#" class="btn btn-sm btn-circle btn-outline-danger"
            title="Delete" onclick="confirm('Are you sure?')"><i
                class="fa fa-times"></i></a>
    </td>
</tr>
<?php endforeach ?>
@php
    else:

    endif
@endphp

Error --
Parse Error : syntax error, expecting T_ENDIF on line 3
  1 | <?php
  2 |                                         if (count($contacts)):
> 3 |                                     ?>
    |                                      ^

**Comment by shufo** [comment]
Currently there is no support for `if~else` conditional block inside `@php` directive.

Please use raw blade directives like this

```blade
@if (count($contacts))

  @foreach ($contacts as $id => $contact)
	<tr>
	    <th scope="row">1</th>
	    <td>{{ $contact['name'] }}</td>
	    <td>{{ $contact['phone'] }}</td>
	    <td>alfred@test.com</td>
	    <td>Company one</td>
	    <td width="150">
	        <a href="{{ route('contacts.show', $id) }}"
	            class="btn btn-sm btn-circle btn-outline-info" title="Show"><i
	                class="fa fa-eye"></i></a>
	        <a href="form.html" class="btn btn-sm btn-circle btn-outline-secondary"
	            title="Edit"><i class="fa fa-edit"></i></a>
	        <a href="#" class="btn btn-sm btn-circle btn-outline-danger"
	            title="Delete" onclick="confirm('Are you sure?')"><i
	                class="fa fa-times"></i></a>
	    </td>
	</tr>
  @endforeach
@else

@endif
