### ISSUE TITLE
Desired format not provided.

### ISSUE THREAD

**Issue by mikebronner** [shufo/vscode-blade-formatter#67]
Hi, thanks for the package. Unfortunately it currently does not provide a format that would help our code style. Would you be open to adding an additional style? I have tried all the provided styles, but the `force` style got me the closest, but not exactly what I am needing for our team.

### Template

```php
<div class="test" id="test2">
    Check this format issue.
</div>
```

After formatting looks like this:

```php
<div class="test"
    id="test2">
    Check this format issue.
</div>
```

I would like it to format like this instead:

```php
<div
    class="test"
    id="test2"
>
    Check this format issue.
</div>
```

This would also go for single attributes, for example:

```php
<div
    class="test"
>
    Check this format issue.
</div>
```

### Environment

VSCode: Insiders 1.54.0
Plugin: 0.7.0
Laravel: 8.x
PHP: 7.4.x

**Comment by mikebronner** [comment]
**bump**

**Comment by mikebronner** [comment]
bump

**Comment by shufo** [comment]
@mikebronner 
Sorry for the late reply!

You can get the above style by set the `Wrap Attributes` option to `force-expand-multiline`.

```blade
<div
    class="test"
    id="test2"
>
    Check this format issue.
</div>
```


One thing to note is that if there is only one attribute, it will not expanded and remains inline.

```blade
<div class="test">
    Check this format issue.
</div>

```

**Comment by mikebronner** [comment]
@shufo thanks for the tip. Unfortunately it still behaves a bit strange in the following example:

```php
                            <div class="ml-4 text-lg font-semibold leading-7"><a
                                    class="text-gray-900 underline dark:text-white"
                                    href="https://laravel.com/docs"
                                >Documentation</a></div>
```

I would really like to see it put each tag on its own line, as well as the content of each tag on its own line as well:

```
                            <div class="ml-4 text-lg font-semibold leading-7">
                                <a
                                    class="text-gray-900 underline dark:text-white"
                                    href="https://laravel.com/docs"
                                >
                                    Documentation
                                </a>
                            </div>
```

Other than that it's really close. Thanks :)
