### ISSUE TITLE
Format and Color bug caused by <style> element

### ISSUE THREAD

**Issue by Exconde** [shufo/vscode-blade-formatter#671]
## Template

```
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <style type="text/css">
        @yield('template_fastload_css') 
        
        @if (Auth::User() && Auth::User()->profile && Auth::User()->profile->avatar_status == 0)
            .user-avatar-nav {
                background: url({{ Gravatar::get(Auth::user()->email) }}) 50% 50% no-repeat;
                background-size: auto 100%;
            }
        @endif

        .user-avatar-nav-2 {
            background-size: auto 100%;
        }
    </style>
    
    <script>
        window.Laravel = {!! json_encode([
            'csrfToken' => csrf_token(),
        ]) !!};
    </script>
</head>
```

## Context (Environment)

The formatter freaks out when a Blade Directive (@if or @yield) is put inside a <style> element. 

```
"bladeFormatter.format.enabled": true
"bladeFormatter.format.indentSize": 4
"bladeFormatter.format.sortTailwindcssClasses": false
"bladeFormatter.format.useTabs": false
"bladeFormatter.format.wrapAttributes": "auto"
"bladeFormatter.format.wrapLineLength": 120
```

## Description

The formatter freaks out when a Blade Directive (@if or @yield) is put inside a <style> element. 
Blade {{ }} and {!! !!} inside the <style> element can also cause this issue.

Almost all code after the <style> element loses it's color coding. 
The first Blade Directive inside also doesn't get line breaked correctly.
CSS elements after the <style> element are still formatted correctly though.

Other than the first Blade Directive inside the <style> element, the rest of the following code seems to be formatted correctly.

**Comment by shufo** [comment]
Directives in style tags are not currently supported. That is why this happens.
I will include a fix in the soon release as I think formatting inside style tags is necessary. Thank you very much.

**Comment by shufo** [comment]
Fixed at https://github.com/shufo/vscode-blade-formatter/releases/tag/v0.20.9
