### ISSUE TITLE
format inside nowdoc/heredoc

### ISSUE THREAD

**Issue by jerothor** [shufo/vscode-blade-formatter#681]
is there any way i can get this to format html strings used inside heredoc/nowdoc?

e.g.:

```php
public function render()
{
    return <<<'blade'
        <div class="alert alert-danger">
            {{ $slot }}
        </div>
    blade;
}
```

**Comment by shufo** [comment]
Sorry, there is currently no way to format blade code inside php. 
This extension is for blade files only.
