### ISSUE TITLE
[Formatting Bug]: @error directive forces newline

### ISSUE THREAD

**Issue by jerothor** [shufo/vscode-blade-formatter#699]
### Platform

Windows

### Template before formatting

```blade
@error('password') <div class="invalid-feedback">{{ $message }}</div> @enderror
```

### Template after formatting

```blade
@error('password')
    <div class="invalid-feedback">{{ $message }}</div>
@enderror
```

### Expected Behaviour

the error directive should not force newlines

it should work just like the `@if` directive, where i can have it all on a single line if i want

**Comment by shufo** [comment]
Linked issue: https://github.com/shufo/blade-formatter/issues/791
