### ISSUE TITLE
@props in laravel is not being formatted correctly

### ISSUE THREAD

**Issue by MohammadxAli** [shufo/vscode-blade-formatter#70]
Hi, thanks for your awesome extension.
There's an issue that I ran into when trying to format a blade file that has `@props` in it.
Here's an example of file:
```
@props([
    'variant'   => 'primary',
    'colors'    => [
        'primary'   => 'btn-primary',
        'secondary' => 'btn-secondary',
        'danger' => 'btn-danger',
    ]
])

<button {{$attributes->merge(['class' => "btn {$colors[$variant]}"])}}>
    <span>{{ $slot }}</span>
</button>

```
After formatting it turns into this:
```
@props([
'variant' => 'primary',
'colors' => [
'primary' => 'btn-primary',
'secondary' => 'btn-secondary',
'danger' => 'btn-danger',
]
])

<button {{ $attributes->merge(['class' => "btn {$colors[$variant]}"]) }}>
    <span>{{ $slot }}</span>
</button>
```

And here's a screencast:

https://user-images.githubusercontent.com/67554982/109470248-68f39e00-7a84-11eb-906b-49c2d0b6e149.mp4

**Comment by shufo** [comment]
Just released [v0.7.2](https://marketplace.visualstudio.com/items?itemName=shufo.vscode-blade-formatter) with `@props` directive support.
@MohammadxAli thanks for reporting issue!
