### ISSUE TITLE
[Formatting Bug]: It replaces the code!

### ISSUE THREAD

**Issue by tomickigrzegorz** [shufo/vscode-blade-formatter#703]
### Platform

Windows

### Template before formatting

```blade
@if ($env)
  <link rel="stylesheet" href="{{ mix('/css/dev/dev.css') }}" />
  <script src="{{ mix('/js/dev/dev.js') }}"></script>
@endif
```

### Template after formatting

```blade
@if ($env)
  <link rel="stylesheet" href="{{ mix('/css/dev/dev.css') }}" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.3/leaflet.js"></script>
@endif
```

### Expected Behaviour

Changed dev file to leaflet.js script!!! The leaflet file is in head. So it somehow magically takes it from head and replaces it at the bottom of the page.
I checked with an older version of the extension and everything is ok, it formats correctly.

**Comment by shufo** [comment]
Thanks @tomickigrzegorz
Just released https://github.com/shufo/vscode-blade-formatter/releases/tag/v0.20.12 to revert regression in https://github.com/shufo/vscode-blade-formatter/releases/tag/v0.20.11.

**Comment by tomickigrzegorz** [comment]
Thanks for your quick response.
I checked version v0.20.12 works fine, but just in case I turned off auto-update in vscode ;)
