### ISSUE TITLE
[Formatting Bug]: 

### ISSUE THREAD

**Issue by SantanuDatta** [shufo/vscode-blade-formatter#726]
### Platform

Windows

### Template before formatting

```blade
@extends('backend.layout.template')
```

### Template after formatting

```blade
ii@extends('backend.layout.template')
```

### Expected Behaviour

dont really understand why is it adding 'ii' after format on save

**Comment by zohaibappedology1** [comment]
This is ben calling you from **Medicare Health Insurance Department** how are you doing today basically the purpose of this call is to make sure that if you have received your new Medicare card the black and white with a golden chip on
