### ISSUE TITLE
issue formatting Html code inside a @if in a @for loop

### ISSUE THREAD

**Issue by LeonardoLpds** [shufo/vscode-blade-formatter#73]
I found a issue that appears to only occurs in a specific layout.
when there is html code in an **if** inside of a **for loop**.

```
@for ($i = 0; $i < $count; $i++)
    @if($i != 0)
        <div>
            {{ $i }}
        </div>
    @endif
@endfor
```

 After formatting, the code above turns into this:

```
@for ($i = 0; $i < $count; $i++)
    @if ($i != 0) <div>
    {{ $i }}
    </div> @endif
@endfor
```
It's like the div is ignored and pushed over the if statement 
I did some variations of this, and the issue only occurs in that condition, **for > if > html**. 
Things like change the **"for"** for a **"foreach"** works as normal

**Comment by shufo** [comment]
I also confirmed that below template 

```blade
<div>
    @for ($i = 0; $i < $count; $i++)
        @if ($i != 0) 
			<div>
        		{{ $i }}
        	</div> 
		@endif
    @endfor
</div>
```

will format into 

```blade
<div>
    @for ($i = 0; $i < $count; $i++)
        @if ($i != 0) <div>
        {{ $i }}
        </div> @endif
    @endfor
</div>
```

Thank you for reporting the issue @LeonardoLpds

**Comment by shufo** [comment]
Now fixed at https://github.com/shufo/vscode-blade-formatter/releases/tag/v0.7.25
