### ISSUE TITLE
[Feature]: disable single quotation 

### ISSUE THREAD

**Issue by kmilo2622** [shufo/vscode-blade-formatter#732]
Hello! Thank you so much for this incredible extension.

### Description

Is it possible to use double quotes? When I have a file with all the blade elements on double quotation marks, this plugin always replace them with single marks when I indent, ¡that's horrible! XD

### Suggested Solution

I would like to choose this behaviour and choose which quotes I would like to use.

### Alternatives

Also would be good not to replace the quotation marks instead of doing anything too complex

**Comment by kmilo2622** [comment]
Please don't close it, does somebody knows how to prevent this behaviour?

**Comment by shufo** [comment]
Hi @kmilo2622 
Currently this behaviour is not implemented in vscode-blade-formatter but already implemented in https://github.com/shufo/blade-formatter. Will be merged soon.

**Comment by shufo** [comment]
Released `No Single Quote` option at https://github.com/shufo/vscode-blade-formatter/releases/tag/v0.23.0

**Comment by kmilo2622** [comment]
Thank you so much! it works great!
