### ISSUE TITLE
[Formatting Bug]: Array to object into optional chaining

### ISSUE THREAD

**Issue by stefvw93** [shufo/vscode-blade-formatter#746]
### Platform

MacOS

### Template before formatting

```blade
<div>
  {{ ($value ?: null)?->someProperty }}
</div>
```

### Template after formatting

```blade
<div>
  {{ ($value ?: null)?->someProperty }}
</div>
```

### Expected Behaviour

Formatting does not break, but vscode shows an error popup:

```
Parse Error : syntax error, unexpected '?->' (T_NULLSAFE_OBJECT_OPERATOR), expecting ';' on line 1 > 1 | <?php echo ($value ?: null)?->someProperty ?> | ^
```

**Comment by shufo** [comment]
It seems php parser used in this package can't parse syntax. 

```bash
 $  node
Welcome to Node.js v16.16.0.
Type ".help" for more information.
> const parser = require('php-parser')
undefined
> const target = `($value ?? null)?->someProperty;`;
undefined
> const eval = parser.parseEval(target)
Uncaught:
[SyntaxError: Parse Error : syntax error, unexpected '?->' (T_NULLSAFE_OBJECT_OPERATOR), expecting ';' on line 1
] {
  lineNumber: 1,
  fileName: 'eval',
  columnNumber: 16
}
```

refs: https://github.com/glayzzle/php-parser/issues/1003

If there is no other work around syntax, please use `Blade Formatter > Format: No PHP Syntax Check` option.
It will suppress syntax error.

<img width="623" alt="image" src="https://github.com/shufo/vscode-blade-formatter/assets/1641039/436a86b1-e9b1-44f7-b4b4-102f32b0c48f">

Configuration file: `.bladeformatterrc.json`

```json
{
    "noPhpSyntaxCheck": true
}
```

Or using ignore directive will suppress the error.

```blade
{{-- blade-formatter-disable --}}
<div>
    {{ ($value ?: null)?->someProperty }}
</div>
{{-- blade-formatter-enable --}}
```
