### ISSUE TITLE
Php 8 nullsafe operator doesnt work

### ISSUE THREAD

**Issue by volovodenko** [shufo/vscode-blade-formatter#75]
## Template

{{ $entity->executors->first()?->name() }}

## Context (Environment)
NAME="Linux Mint"
VERSION="18.3 (Sylvia)"
LARAVEL 8.12

## Description
Parse Error : syntax error, unexpected '->' (T_OBJECT_OPERATOR) on line 1 > 1 | <?php echo $entity->executors->first()?->name() ?> | ^

**Comment by shufo** [comment]
same with https://github.com/shufo/vscode-blade-formatter/issues/61
we need to wait for upstream dependency to be support php 8.

**Comment by shufo** [comment]
Just released [v0.7.4](https://marketplace.visualstudio.com/items?itemName=shufo.vscode-blade-formatter) with null safe operator support. It would be nice if it works properly on your platform.
