### ISSUE TITLE
[Bug]: Error on update to version v.0.23.0

### ISSUE THREAD

**Issue by Blackart-glitch** [shufo/vscode-blade-formatter#765]
### Expected Behavior

simple update with a reload of vscode

### Notifications:

![image](https://github.com/shufo/vscode-blade-formatter/assets/64565324/93129fa7-38f4-47ca-97d5-fb8c1b1e0f47)

### LOGS:

![image](https://github.com/shufo/vscode-blade-formatter/assets/64565324/829f0d5d-0238-4c09-ab94-196c7296e40c)

### Additional Context

version: 0.23.0
platform: windows 10p

**Comment by shufo** [comment]
@Blackart-glitch 
Please try this method as it may help
https://github.com/PowerShell/vscode-powershell/issues/4474#issuecomment-1706581240
