### ISSUE TITLE
[Formatting Bug]: Scoped slots opening tag improperly colored.

### ISSUE THREAD

**Issue by eavonius** [shufo/vscode-blade-formatter#768]
### Platform

Windows

### Template before formatting

```blade
<x-my-component>
  <x-slot:mySlot>
    Here's some content!
  </x-slot>
</x-my-component>
```

### Template after formatting

```blade
<x-my-component>
  <x-slot:mySlot>
    Here's some content!
  </x-slot>
</x-my-component>
```

### Expected Behaviour

This is when using scoped slots as described [in the laravel docs here](https://laravel.com/docs/9.x/blade#scoped-slots). The closing ```</x-slot>``` tag is properly colored, but the opening ```<x-slot:mySlot>``` tag is colored red (as though there's an error).

**Comment by shufo** [comment]
Thanks for creating the issue @eavonius 

But this package has no feature like syntax coloring. 
Maybe it's feature of blade highlighting package like [Laravel Blade Snippet](https://marketplace.visualstudio.com/items?itemName=onecentlin.laravel-blade).

**Comment by eavonius** [comment]
Ah ok. Thanks @shufo I'll contact them over there.
