### ISSUE TITLE
[Bug]:  instalo la extension y me deshabilita colores de el tema que uso

### ISSUE THREAD

**Issue by StiwarOspina** [shufo/vscode-blade-formatter#774]
### Description

Cuando instalo la extension se instala normal, pero en el archivo .blade automaticamente me convierte todas las letras en blancas lo cual molesta 

### Expected Behavior

que se instale normal y no me afecte el tema que estoy usando haciendo referencia a los colores de los textos etc.., se mantengan los colores del tema que manejo y siga formateando normal

### Actual Behavior

me convierte todas las letras del archivo .blade en blancas 
con la extension inhabilitada
![image](https://github.com/shufo/vscode-blade-formatter/assets/142843264/8e25d882-4192-4e2e-875b-41174374b777)

con la extension habilitada
![image](https://github.com/shufo/vscode-blade-formatter/assets/142843264/ce921a1f-3be7-4477-b606-19c2881fb5e7)

**Comment by shufo** [comment]
Maybe related to https://github.com/shufo/vscode-blade-formatter/issues/56
Install the blade snippet plugin may solve the issue.
