### ISSUE TITLE
[Feature]: TODO comments highlight

### ISSUE THREAD

**Issue by negativems** [shufo/vscode-blade-formatter#776]
### Description

Add "TODO:" comment highlighting for blade syntax.

Also add it on the problems tab as a warning.

### Suggested Solution

Something like this

![image](https://github.com/shufo/vscode-blade-formatter/assets/20746840/48039f0d-9472-4c3a-a2c3-0e5759756d4a)

### Alternatives

Maybe there are other extensions that could make this

**Comment by shufo** [comment]
Thanks for suggesting the feature.
This is good feature but I think this feature should not be included in this extension's scope. Let this feature in other extension maybe the good way.
