### ISSUE TITLE
[Formatting Bug]: syntax error with double curly braces

### ISSUE THREAD

**Issue by ionutdrg45** [shufo/vscode-blade-formatter#790]
### Platform

Windows

### Template before formatting

```blade
<div class="google-iframe-box">
    {{!! $girl->city->google_iframe !!}}
</div>
```

### Template after formatting

```blade
<div class="google-iframe-box">
    {{!! $girl->city->google_iframe !!}}
</div>
```

### Expected Behaviour

It should format the entire file but instead I get this error: 
![image](https://github.com/shufo/vscode-blade-formatter/assets/52635963/72367484-9eb2-4d00-86e9-ef40b86c0fa7)
Parse Error : syntax error, unexpected '!', expecting ';' on line 1
> 1 | <?php echo !! $girl->city->google_iframe !! ?>
    |                                         ^

**Comment by shufo** [comment]
It seems syntax error.

To use unescaped expression, you must use single curly braces for expression.

```blade
<div class="google-iframe-box">
    {!! $girl->city->google_iframe !!}
</div>
```

https://laravel.com/docs/10.x/blade#displaying-unescaped-data
