### ISSUE TITLE
issues with custom if blade directives 

### ISSUE THREAD

**Issue by JrBoc** [shufo/vscode-blade-formatter#80]
## Context (Environment)

Custom if blade directives are not being formatted correctly.

Pre-Format
![image](https://user-images.githubusercontent.com/41932859/113116840-6bdadd80-9240-11eb-907d-14cb350d6d62.png)

Post-Format
![image](https://user-images.githubusercontent.com/41932859/113116885-76957280-9240-11eb-95a6-35e769dfec68.png)

## Description

I've created custom if blade directives based on [this](https://laravel.com/docs/8.x/blade#custom-if-statements)

**Comment by aaronjpitts** [comment]
Is there a way to get the formatter to respect custom directives?
