### ISSUE TITLE
[Bug]: After the installation, blade files lose syntax highlight!

### ISSUE THREAD

**Issue by trollfalgar** [shufo/vscode-blade-formatter#823]
### Description

The formatting is working. But some conflict made blade files lose syntax highlight!

![codede](https://github.com/shufo/vscode-blade-formatter/assets/441455/aa1a84df-b0c3-4ab2-8353-59bb9a9f677c)

### Expected Behavior

Not lose syntax highlight!

### Actual Behavior

Lose syntax highlight!

### Additional Context

Version: v0.24.1
SO: Windows (WSL)

**Comment by shufo** [comment]
This extension does not have syntax highlight feature.
Please try using [Laravel Blade Snippet](https://marketplace.visualstudio.com/items?itemName=onecentlin.laravel-blade) for Syntax highlighting.

**Comment by trollfalgar** [comment]
> This extension does not have syntax highlight feature.
> Please try using [Laravel Blade Snippet](https://marketplace.visualstudio.com/items?itemName=onecentlin.laravel-blade) for Syntax highlighting.

I know it doesn't have.
But when I install it, blade files lose syntax highlight.
Some conflict must be happening.
I'll investigate.

**Comment by shufo** [comment]
Related issue:
https://github.com/shufo/vscode-blade-formatter/issues/56#issuecomment-1662981245

There is multiple highlight plugin for blade. I'd recommend to use only Laravel Blade Snippet cause it's confirmed working with this extension.

**Comment by jkvithanage** [comment]
> This extension does not have syntax highlight feature. Please try using [Laravel Blade Snippet](https://marketplace.visualstudio.com/items?itemName=onecentlin.laravel-blade) for Syntax highlighting.

I had the same issue with syntax highlighting. [Laravel Blade Snippet](https://marketplace.visualstudio.com/items?itemName=onecentlin.laravel-blade) solved it!

In summary, you should install both Laravel Blade Formatter and Laravel Blade Snippet extensions to get formatting and syntax highlighting.

**Comment by DamianSuess** [comment]
I ran into the same issue as well after installing the extension, all the text went to "white".

The noticeable difference was that it updates the file's _Language Mode_ from **PHP** -> **Blade**.  In the short term, I can manually change the Language Mode by clicking it the bottom status bar.

## Reproduce

1. Install the extension
   * No syntax highlighting; _language mode: PHP_
2. Disable the extension
   * Highlighting comes back; _language mode: Blade_
3. Reenable the extension
   * No syntax highlighting again; _language mode: PHP_

### Installed

![image](https://github.com/shufo/vscode-blade-formatter/assets/1216684/e51a0894-5009-403a-afff-1e4cf7addd67)

### Disabled/Uninstalled

![image](https://github.com/shufo/vscode-blade-formatter/assets/1216684/abe30896-6ae6-497e-bd8e-10506a58f79c)
