### ISSUE TITLE
[Formatting Bug]: spaces contained in string are broken up when wrapping text.

### ISSUE THREAD

**Issue by rikvdh** [shufo/vscode-blade-formatter#835]
### Platform

Windows

### Template before formatting

```blade
@canany([
    'Lorem ipsum dolor sit amet',
    'consectetur adipiscing elit',
    'Phasellus magna urna',
    'fermentum sit amet lectus nec',
    'aliquet finibus velit',
    ])
@endcan
```

### Template after formatting

```blade
@canany(['Lorem ipsum dolor sit amet', 'consectetur adipiscing elit', 'Phasellus magna urna', 'fermentum sit amet lectus
    nec', 'aliquet finibus velit'])
@endcan
```

### Expected Behaviour

The spaces contained inside strings should not be broken up. There are multiple ways of formatting this, but the whitespace in strings should be retained as it.

**Comment by shufo** [comment]
Thanks for the report!
It should be fixed. I'll look into it.
