### ISSUE TITLE
[Bug]: HTML syntax highlighting and html suggestions in .blade.php is gone when I install this extension

### ISSUE THREAD

**Issue by Maaz0313** [shufo/vscode-blade-formatter#841]
### Description

When I install this extension, the syntax highlighting and suggestions of HTML in .blade.php is gone

https://github.com/shufo/vscode-blade-formatter/assets/94098890/89fdc707-47fc-45e4-bd27-3165ca87f3ec

https://github.com/shufo/vscode-blade-formatter/assets/94098890/ca8489a0-880d-454e-91e5-8bd1c9306394

### Expected Behavior

HTML syntax highlighting should not be gone.

### Actual Behavior

When I install this extension, the syntax highlighting of HTML in .blade.php is gone.

**Comment by Seinzzz** [comment]
I also had the same problem, then I installed this extension to get “Syntax Highlight support”. this is an alternative to fix the bug

![image](https://github.com/shufo/vscode-blade-formatter/assets/104157251/707829a2-4161-4893-87ad-a16b3fee48f8)

**Comment by jasonmarlin** [comment]
Same issue here on a new VS Code install - not sure what changed, but I have highlighting in previous installs.

**Comment by Maaz0313** [comment]
Please update this extension

**Comment by ahmadyogi543** [comment]
Is there any update on this?
