### ISSUE TITLE
[Bug]: Problem with syntax

### ISSUE THREAD

**Issue by Carlosvega17** [shufo/vscode-blade-formatter#844]
### Description

Hello! I wanted to comment on a syntax issue that is occurring in my project.

I have the code:

 "class="navbar-brand" href="{{ route('livewire.dashboard-user') }}"
          :active="request()->routeIs('dashboard')" style="color: #fff;">
          <img src="{{ asset('img/logoJas.png') }}"> TicketJas
"

What happens is that when I have the extension active, and hit save to make the code work, for some reason it saves and alters the ":active="request()->routeIs('dashboard')"" going from that, to the next ":active="request() - > routeIs('dashboard')"" basically puts spaces between the arrow that connects the request with routeIs "request() - > routeIs".
When this happens, the syntax error "Syntax error: unexpected token '>'PHP(PHP2014)" is generated, in order to solve it for the moment what I do is deactivate the extension and save the progress without altering the code and do not generate the error.

I really appreciate if you can help me, to know if I am doing something wrong or if it is a general bug.

### Expected Behavior

That when I save the code progress, the extension does not alter the following ":active="request()->routeIs('dashboard')"", that the arrow stays together without empty spaces being added.

### Actual Behavior

When I save code progress with the extension enabled, the extension adds empty spaces between the arrow and the code.

No error: ":active="request()->routeIs('dashboard')""

The error is generated when saving: ":active="request() - > routeIs('dashboard')""

### Additional Context

Platform: Windows 11 Home (version: 23H2)

Laravel Blade formatter v0.24.2

-----------------------VS - info------------------------------
Version: 1.89.0 (user setup)
Commit: b58957e67ee1e712cebf466b995adf4c5307b2bd
Date: 2024-05-01T02:09:22.859Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631
----------------------------------------------------------------

**Comment by LTIOfficial** [comment]
Same issue here within Laravel 11.

```
<nav-link	
	href="/"
	:active="request()->is('/')"
>
	Home
</nav-link>
```

`:active="request()->is('/')"` becomes `:active="request() - > is('/')"`, which breaks the code.
