### ISSUE TITLE
[Formatting Bug]: Slow on big HTML files

### ISSUE THREAD

**Issue by khalyomede** [shufo/vscode-blade-formatter#863]
### Platform

Linux

### Template before formatting

```blade
Too long template (for example the ones of Keen Themes or any admin Saas template).
```

### Template after formatting

```blade
Too long.
```

### Expected Behaviour

The plugin takes several minutes (sometimes never finishes in a dozens minutes) to complete formatting a huge HTML page.

**Comment by shufo** [comment]
To avoid this problem, it is recommended to split huge blade files into components.
https://github.com/shufo/blade-formatter/issues/616

You can use anonymous component to split large blade file.
https://laravel.com/docs/11.x/blade#anonymous-components
