### ISSUE TITLE
Issue with formatting in script tag

### ISSUE THREAD

**Issue by iabhiyaan** [shufo/vscode-blade-formatter#99]
# While Formatting
    <script type="text/javascript">
        const errors = @json($errors - > all());
        console.log(errors, errors.length)
    </script>
    
# Expected
    <script type="text/javascript">
        const errors = @json($errors->all());
        console.log(errors, errors.length)
    </script>

**Comment by shufo** [comment]
This behaviour is now fixed in https://github.com/shufo/vscode-blade-formatter/releases/tag/v0.7.11
@iabhiyaan Thank you for reporting the issue!
